### ISSUE TITLE
Judgement at the Eye Of Eternity + Heroic Judgement at the Eye of Eternity

### ISSUE THREAD

**Issue by WhitemaneIsa** [gamefreedomgit/Frostmourne#975] opened 2024-06-17 20:14 UTC
https://www.wowhead.com/wotlk/quest=13384/judgment-at-the-eye-of-eternity
https://www.wowhead.com/wotlk/item=44650/heart-of-magic

https://www.wowhead.com/wotlk/quest=13385/heroic-judgment-at-the-eye-of-eternity
https://www.wowhead.com/wotlk/item=44651/heart-of-magic

Both failing to drop the quest item sometimes, droprate should be 100%.

**Comment by Riztazz** [comment] 2024-08-27 10:00
Fixed, will close once it's live

**Comment by WhitemaneChronus** [comment] 2024-09-05 23:25
Current issue is that if a player who is not eligible for the quest item (for example not having the quest) clicks on the heart box, it shows empty and then disappears entirely. Other players will not be able to get their quest item.

**How it should work:**

Anyone who has the quest + key according to their quest should be able to see the blue heart and loot their quest item.

**Comment by Riztazz** [comment] 2024-09-06 06:39
Now that's a report, i'll re-assign and take a look

**Comment by Riztazz** [comment] 2024-09-06 08:46
I cannot reproduce this :(

**Comment by WhitemaneChronus** [comment] 2024-09-06 19:33
I tested as following:
have key + quest on char A, and none on the other (char B). B should not be eligible for quest item. 
after the boss is dead and blue heart appears, open it with B.

**Comment by WhitemaneChronus** [comment] 2024-09-06 19:58
I'm testing now again and it seems to happen on 10ascended, but on 10 normal it worked fine.

**Comment by Riztazz** [comment] 2024-09-07 08:04
I think i know what's happening :P Ascended mode is treated as 25man (loot-wise) and quest-wise, so the heart doesn't "drop" because noone in party has a 25 man version of the quest

**Comment by WhitemaneChronus** [comment] 2024-09-07 11:13
That´s not the case.
https://youtu.be/2A7YVVH-x0E
here´s a group of two. One (Chronus) has the quest Heroic Judgment at the Eye of Eternity + Heroic Key to the Focusing Iris and the other (Sunlute) only the hc key and not the quest. Therefore only Chronus should be able to loot the heart.
If you skip to last few seconds, when I have opened the box with sunlute (player not eligible for the item) it shows empty (which is correct) but then heart disappears before eligible ones get to loot it.

**Comment by Riztazz** [comment] 2024-09-08 07:08
I'll check it out on monday

**Comment by Riztazz** [comment] 2024-09-09 09:59
yup, reproduced it, thanks!

**Comment by Riztazz** [comment] 2024-09-09 11:29
Can you test on PTR once it has been updated? I've pushed a fix

**Comment by WhitemaneChronus** [comment] 2024-09-10 16:54
Heart is not disappearing on PTR anymore.

Scenario 1: Both players have both keys, A has both quests, B doesnt; heart does not disappear. However, it is dropping the item for both quests. players who arent eligible cannot loot it. (i am not sure if this intended or not, in the past players could only complete heroic quest in 10 asc). 
Player A completed both quests, B none.

Scenario 2: Both players have both keys; A has both quests, B has normal quest only;
B completed normal quest, A completed both quests

![image](https://github.com/user-attachments/assets/d830373d-7c49-48fe-ac1e-fc51f63feeed)

**Comment by Riztazz** [comment] 2024-09-11 06:40
It is intended, it was supposed to drop both loot-modes, quest-wise too, but the way code was structured it prevented 10man quest items from dropping. Talked with ultranix about it :)

**Closed by Riztazz** 2024-09-11 06:40 UTC
Labels: Critical Prio
