### ISSUE TITLE
[PALADIN] Hand of Sacrifice / Divine Sacrifice

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1369] opened 2024-07-15 13:55 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** both effects work in a similar manner, so I'll post them together. Issue is, if the target that has sacrifice buff from the paladin, has also an absorb effect at the moment of taking dmg, sacrifice transfers no dmg, thus breaking no cc that breaks on taking dmg.

Also currently if the TRANSFERED dmg gets absorbed on the caster Paladin, CC-s don't break.

![image](https://github.com/user-attachments/assets/2f8574ba-36c2-4fa6-88cd-444087fad932)

Also the 100% caster HP threshold isn't present currently.

**How to reproduce:** deal dmg to a target that has absorb on them while also having a sacrifice effect.
Deal dmg to a target while  the caster paladin has an absorb on them.

**How it should work:** Sacrifice effects should transfer '0' dmg to the paladin if the dmg was absorbed fully, thus breaking CC-s that break on dmg.

Also if the transfered dmg has been fully absorbed, cc that should break on dmg should still break - since dmg has been taken

Breaking of CC should happen on taking dmg, regardless of the source of the original dmg (before transfer) -> hellfire, seal of blood / martyr, etc.

Warlock -> soul link to pet -> sacrifice onto pet ->dmg to paladin via dmg to warlock through soul link - should also work - this is important in PvP as high lvl priests, shamans etc dispel sacrifice, but from an invisible succubus they can't - unless they use mass dispel, which can be evaded with good positioning of the pet.

Hand of Sacrifice should only transfer DMG equal to 100% of caster max HP, at which point the aura should be canceled.

**Database links:** https://www.wowhead.com/wotlk/spell=6940/hand-of-sacrifice     https://www.wowhead.com/wotlk/spell=64205/divine-sacrifice

Video:

https://www.warcraftmovies.com/movieview.php?id=115963

~ 16:30 - in floating combat text, 0 dmg can be seen, yet the Repentance breaks upon taking the 0 dmg.

Possible fix is setting CC-s that break on dmg to break if dmg >= 0.

**Comment by alemae96** [comment] 2024-07-15 19:56
It's a bit confusing tbh. You say that 0 dmg should be transferred if it was absorbed, but in your next sentence you say that if the dmg was fully absorbed, then cc should break bc dmg was taken. If it was fully absorbed, no dmg would be taken, meaning cc should not break. Also in the video, I don't see anyone with Repentance, and yours has no CD on it on your bars. Also at the same time that you mention for the video, there was a mass dispell that can be seen on the ground. So makes me believe it was dispelled and not broken. But you have no meters to show and video quality is rough, so hard to see fully

**Comment by haephaistoss** [comment] 2024-07-15 20:20
You're totally mixing it up... 16:34, you see 0 dmg multiple times in floating combat text.

On Blizz's part, if the dmg was fully absorbed - so no actual dmg was taken, sacs transferred 0 dmg - which is still DMG, that is equal to 0, and CC-s that break on dmg, break if you take dmg, but that dmg doesn't have to be greater than 0. It simply happens, that most of the time hits deal more than 0 dmg.

![image](https://github.com/user-attachments/assets/456bb430-5f8e-4c52-9bde-1f54be090aa3)

![image](https://github.com/user-attachments/assets/e98ebd56-9450-458d-83f0-b7ea367fe995)

![image](https://github.com/user-attachments/assets/0f64ac31-1510-4aae-a012-1324b9adb4fb)


THe guy making the recording gets repentanced, sacs his teammate eforehand, and gets broken out by 0 dmg multiple times being taken.

It can be quite clearly seen in the video, he takes 0 dmg 3 times, the first one before repentance, and the 2nd, and 3rd after repentance, these ones breaking it.

He even gives you subtitles to understand what's going on.

Rogue gets PW:S, Sac, Paladin gets Rep, rogue gets dmg that is absorbed by PW:S, and Sac transfers 0 dmg multiple times breaking the enemy rep.

CCs that break on dmg should break even if the dmg that breaks them gets fully absorbed, same with fear effects that use base hp % to determine the threshold at which they are required to break. Absorb doesn't, and shouldn't matter in these contexts, for fairly obvious reasons.

**Comment by yeagerca** [comment] 2024-07-15 20:31
On Frostmourne, when a spell is fully absorbed, such as during Divine Shield, it is entered into the combat log as SPELL_MISSED. As far as I know, this is intended behavior.

I made a WeakAura to calculate the total damage transferred by Hand of Sacrifice, I'll put the export here in case anyone wants to reuse the code to test this bug.

On a separate note, it seems like Hand of Sacrifice does not have a maximum amount of damage transferred unlike what the tool tip states. You can transfer much more than your maximum health over the duration by healing or absorbing damage (and/or dying).
`!WA:2!nJ1tVXrsv8mYse0OfHJxKHyGLEn5FEXzWEsiO9qq4XEC8ez7XBpJtYcHTNQ7U6PR4E6U2QQzSNiyrXcK8zFaXfUmO9gNSGVa(csCHsw8jiFeYroXRQU7zANPTJZblrlzpvx1R(9(F9Evxy1P6mL7uUhCJbeNOWgrDzo4FWvy7v3ZJJfR9lN5F2)dx73ELboD5IOonX7jOpYRBOJGefEN5kAapmSOll0a1LHSWH9k1bT3AyuGWF(rZjIeOGMmui3dZyy3I4qxw)uM8L)3FX)4d(7YJqHo(rSTIiHc7LRUzZQM0jhX4TPUib2UR(NJDIIcCJ2nSQBBClgslq8hyYfiMy6bUrwDWCoQn2VcjKiU1HWmXq1Yo(x6xF37AScoWbXWAb1aeuclkSdouy0dXii7amV446LXdn2gWm(Lnq7DNzPbO(y2SZnIyrIUAI7GabiS9fAtVLvc2Zc2EW25()PxNOpjAb9EVdVqEw8JtXq0NIn3YS2MnLFRwmW00oiAxF5K0)kytmXGt5)JTi0VBQA4fX6GewojdQegfIzjlsV7NdbZgRHcDnI8mAGCyepId2qKbTB6y4I6auxs(T9PFV3g3YjJKZSVGrA3gZ4FXTyjdp4AmofheuZTYd(07VW(UGmR8hZUy5kDb9YowBout0MOoy61gtyQOCeh6e1XgjcIA)AExBCpWy3ORNhzVtSwABZLSwARTwVw1voPlhBnemFtnHdwwVxJ1JApWfYn88AciYwR66BT62RpeVTyyapZgBvD91pAio1CBTFYaEXxRNwN)R8kT2x9UspAzgc8JxCWOfL34y1QkVKID(h2nmXOu8wYF0bFNb6v7ebt7lnKFSCb5I77I5ImBUdHZ1Bwws(tL3wo5(PZyVuLg1nRCuCGULpXflNu(JL3qoV8UY5ywBuRrJQRelc28iMn21xwULCY9(g)RHzfjcuvL6pVrPsLIttcICqbg44zhAnNpjmydqeWUW5wAzFEJOEy2oKGG5H0loHluRzdqSJMOeENb3yx(J2U2kjb3QHzIRhrPYAKqhhhGDe35bzKsI3ice(4qJKNIPdYsWdFyw(QiFizQNHk5iwT4cz4vgiZq6dnMDSO1zhhC1J2yoc8Y5GDc(jucyRJetCKNbSQNSELmI)9odwKAzYURZeB1Z5DoZzV2p5uCixWHdBh3ofWX5yewzPnw6rvphJqCWyg1V85O(PrSxqRvAyDgY)zNd5jX(zO(bNd1Pjizi)NF(EUev9sXNfJ9f2BLirdTNxkYuk6VVs1q32LIuLI(7RuLgDCPiujG)(ktdJbVCIPYwc4cDgWBnx23thR(f(tEFFthFSZoY51L6sRF2kUKoN(9xU(gvwQP161FKv1NaTlBT9MRwBDOR5QRKw8u1Fbu28tlEKlH)cDTXE4YOW(0RH0JBgxMCJix8F7kVbA8gZcrbpb60bkIsEZoymDjOSGJWu1CJ)HOqshDBopq(bRcLTN5ymIJBiy4W2c)REsAxqAoZ4y4sfU89v0OkTlNPIQ5p9gLBEvzD5wYpdgo1Bpd0mdhjuyH9haDXyIBR6V)XtlV9jWR2iNDAZG8z3dMMoLaUCGf3hbxh4zXxPOa966j1)lPBo(WM5oC4AhDZflPSR62ZMmdolhfeXECHcfM41XZId8IVxsL6nBwFd6hQNg1fmYG(68uIRWVYsWRVjMNK9WU6jF1jX3Q5ZtKSJ1R)cW9q86lVQ82mqFuZnqVGJMXtaphMi8Hc6KRYiV04Z6ICbdcYOzZtPZPit)KX05rAh0PKnd3JagulOT9RDIMSDJyUpLHO7)0KbNmKP6(iRVDZ1RTz1ettMRNDyTn3SQPvZ6BrV1fJRTOZEEegpJnhABlS9iPOb5L4RNybF2PSG9iCcCBKwhmh9JgdyQLGme0cYNv(MolMd)VxjrjF91pggBq)HJrLWshPfFPjVGOiM06v5eGLEnejv6O9GsVcsFjr(c5oYV86swErLlpIZ3iho7IDG8TalkdgOsjZZlFVeLOKiwThs8e5WqAYatfPUYFT85YFJ8lOF8zzdZa2hLJaEk7CRc5GJZBh6LdnxebpDG9MD7yJz05olj2TpCHfIJLWhkK5hf42x(KcW5l25SfXzULGJHGFiepoFx6kX5eAKv38tskpD6oT870DnoZP3(DUPetoDMXLPftdP(d54XGvhfnl3t(R0hYrVzEeoEWNebNyXBLBQ0q5lH7F1bxxz3v5ELZtqkFAbjjqesTGWifFYtMkNNm97Nq5CH0R00oWxLOxQmqqCNjpKsns60ZGJJpqlXBlItCHK2)yF5Vt(v2(ysBFXRQeeHCxTchovAAZoDdeKIvuvhNw(NlA6eG4C1iBOpbOcTA4aMUWL6W0kQpW2jqfdi6Oov)5Qkwbo)ZzVc)BORcND4QEusBbok9AmN67vy33OFUFvJsfBc7vXbdOqV66GXOjqS2yHrO(oUA4DC6ccos1844maUulaSMfqMkPt3ogXUvdKigpi2tXyheu)kSDPIlDU4zqcDc6ckzsNsC4o3DDa04Ped(rv3mX62kKEKqSrdFcoWTuXNQU5RIR5amEphm2LNNSoFoF0NWi4E3HqJogPFGaESjt3uxUsoh6dMgXeATiMpUype40nC8bZXUKqO4RXUPcP(YZQM34L2p9Jt26OeVrnWZq)KAQ2R8qo4NREN)8gQTyTwuqFRgGOx3B0hg6LrrDkyoQBGbIiNEXDL9n798zjU0BmUwoUAyd8XJ0U4rEmieaAtd6FyI3eFe1QQP0FWLglBwT6MM7Q7xPCxI7rSa77vXCUh)K7ydfKvmg3Yefq9rti)lTgO6QJehcFejmotcER4Hd7tsE1P4M3V0cLwyQE)NN9)(d`

**Comment by haephaistoss** [comment] 2024-07-15 21:18
Absorb and immune, and miss, and fully resisted are completely different as far as I know.

See with absorb, DMG is registered, amd calculated, with the others, calculation doesn't happen, nor does crit roll etc. They don't even register as hits.

Thanks for the info, I was gonna test that next, but you were faster 🫡

Updated the main post with the information!

**Comment by Piootrek** [comment] 2024-08-19 12:34
Fixed

**Comment by haephaistoss** [comment] 2024-08-19 12:45
yaaaaay <3

**Closed** 2024-08-26 14:41 UTC
Labels: High Prio
