### ISSUE TITLE
Blood Tap + Empowered rune Weapon interaction

### ISSUE THREAD

**Issue by Jairocv** [gamefreedomgit/Frostmourne#1552] opened 2024-08-09 00:02 UTC
https://imgur.com/a/zafwmIf

I have saw a few Frost dk guides, and it is an opener rotation where when they use ERW, the death rune from blood tap its restored as death rune, however, when i use ERW, that death rune is restored as blood rune, so you cant do the 3x Obliterates as its shown in the attached image.

Im not sure if that is a change in the future phases, but im posting it just in case its a bug.

ty

**Comment by Manpower99** [comment] 2024-08-10 13:15
Have been playing FDK since beta, this interaction works fine, blood tap is a buff that you can cancel.
perhaps you messed up your opener idk.

**Comment by Sylanha** [comment] 2024-08-10 13:21
Yeah, this works perfectly fine. I am playing FDK aswell and the picture you posted (the opener) also works as intended. You may have fucked up the rotation, as there shouldn't be an issue.

**Comment by PanJanuszek** [comment] 2024-08-12 16:33
Closing as not a issue basing on other player's comment

**Closed by PanJanuszek** 2024-08-12 16:33 UTC
Labels: Medium Prio
