### ISSUE TITLE
Nax10 Ascended - Tuning / Bugs / loot

### ISSUE THREAD

**Issue by Iramtempus** [gamefreedomgit/Frostmourne#933] opened 2024-06-15 21:20 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Tuning need to be revisited for Ascended, most of the bosses were ok. Raz is bugged (Doesnt have any control, Maex webs 4 not 2(at max).
Patchwerk hits for too much needs to be tweaked. (Couldnt test rest in that quarter as he gatekeeps)
Loatheb is a pretty ok fight health pool is OK but the damage he deals is a bit much not sure how much needs to be tweaked.
When it comes to loot table, there needs to be a higher chance of 25man token. The "Guaranteed" token slot that is in 10man should be 25man or a 50% chance of it being 25man version, it should NOT be part of the regular loot table.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by RadeghostWM** [comment] 2024-06-16 05:31
Agree, the guarantee token slot should be 25-man, for sure.

**Comment by Iramtempus** [comment] 2024-06-16 17:02
Also ascended should drop Valor not Heroism.

**Comment by bandini9** [comment] 2024-06-16 17:44
Maex has always been a fight with RNG aspects, my group managed to kill it after 4-5 attempts iirc, 4 is a lot deffinetly but instead of 2 i'd suggest 3.

I am unsure if Raz was bugged or not but at pull we had little hiccups with Mind control, I thought it was about range.

I consider Loatheb fine for first ID, we pinponned last 20~

Patchwerk... Patchwerk is biggie.... I took 51k hatefulls with my rogue ahh, either it hits hatefull too often or hits too hard. I agree It needs tune.

No opinions on loot I just like to kill big stuff

**Comment by Iramtempus** [comment] 2024-06-16 19:28
I mean Raz is bugged, you should have orbs to control him on 10man due to the lack of priests.
Loatheb can be pingponged which is a work around but kinda meh.
I kind of agree 3 webs would make it better but still be challenging, would not be opposed to it just being the 2 as normal.

**Comment by BorisVolk** [comment] 2024-06-17 15:31
Maex web count is really an issue in 10 man groups even with 3 in coordinated groups 2 healers might get webbed and quite often the tank gets webbed which causes a lot of chaos. 
Patchwerk damage is out of mind right now. Only solution we could think of was a holy paladin spamming holy light on tanks without stop and druids innervating them in a circle. We didn't get to see rest as well and I am kinda sus about Gluth.

**Comment by WhitemaneIsa** [comment] 2024-06-17 17:52
As this is not a bug but a suggestion, I will be closing this issue. Please visit the suggestions area on Discord for Suggestions.

**Closed by WhitemaneIsa** 2024-06-17 17:52 UTC
