### ISSUE TITLE
UH DK pet bugged in arena 2v2

### ISSUE THREAD

**Issue by Jairocv** [gamefreedomgit/Frostmourne#1075] opened 2024-06-23 02:46 UTC
https://imgur.com/a/haxhCd5

Uh pet is getting bugged in the waiting stage on arenas 2v2
1. Just let you summon the pet on the 10-15 left before arena start.
2. It just simply doesnt let you summon the pet in the whole fight, the skill appears disable. It start happening right after I set the Glyph of raise Dead. (added the ss)

**Comment by Meaninglessx** [comment] 2024-06-26 04:14
it is happening outside arena aswell btw even now after applying the new updates

**Comment by Riztazz** [comment] 2024-08-27 08:31
Any chance i could get a video of it happening? Been trying different ways for an hour and can't reproduce it

**Comment by UltraNix** [comment] 2024-09-14 15:35
@Jairocv @Moonlxght69 Still valid?

**Comment by Riztazz** [comment] 2024-09-23 09:31
Closing, no answers

**Closed by Riztazz** 2024-09-23 09:31 UTC
Labels: Dev has a question, High Prio
