### ISSUE TITLE
Hunter pet talents randomly dissapearing

### ISSUE THREAD

**Issue by mariobrose2** [gamefreedomgit/Frostmourne#1016] opened 2024-06-19 20:03 UTC
**Description:**
Sometimes your pet will have no talents when logging in, making you unable to use cds such as Call of the Wild. This forces you to dismiss and resummon to fix it which is annoying.

**How to reproduce:**
Don't know how to reproduce, happens randomly.

**How it should work:**
Pet talents should never dissappear and should load automatically on login

**Comment by UltraNix** [comment] 2024-06-22 14:37
@mariobrose2 Pets is already beside you on login or must be called?

**Comment by mariobrose2** [comment] 2024-06-29 02:01
must be called

**Comment by UltraNix** [comment] 2024-07-01 13:18
I can't reproduce it on different scenarios.
@mariobrose2 It happens often? Maybe in some specific scenario?

**Comment by WhitemaneIsa** [comment] 2024-08-14 19:42
No further complaints/Info, closing.

**Closed by WhitemaneIsa** 2024-08-14 19:42 UTC
Labels: Dev has a question, High Prio
