### ISSUE TITLE
[CORE] DoT Rolling Timer Mechanic

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1247] opened 2024-07-04 13:03 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** In my recent testing DoTs seem to behave in an unintended manner. The issue seems to be global, that's why I'm creating this post:

(All DoTs seem to keep both the caster and target in combat.)
All DoTs seem to deal dmg only if the tick period has elapsed since reapplication instead of the last tick in case of reapplication.
(They all seem to be snapshotting AP / SP, even the ones that should not.)

DoTs I tested and found to be wrong:

Seal of Corruption
Blood Plague
Frost Fever
Ignite (Fire mage)
Serpent Sting 
Righteous Vengeance
Piercing Shots

**How to reproduce:**

**How it should work:** As you can see below from a screenshot of my combatlog on retail classic ptr, the reapplication of the DoT shouldn't interfere with the tick period at all in most cases.
Currently it does. I can keep reapplying the DoT for hours and deal 0 dmg.

Testing on Retail Test server Today:

![image](https://github.com/gamefreedomgit/Frostmourne/assets/67190649/520d1b8e-5408-4aaf-97b8-998f65f62767)

On the PTR today:

![image](https://github.com/gamefreedomgit/Frostmourne/assets/67190649/525695c9-4fe7-49a0-8b15-00affd77e252)

**Comment by slicplaya** [comment] 2024-07-06 04:26
Piercing Shots works completely different from the other dots. It stacks the damage and keeps the duration's separate. Or at least it's supposed too. Serpent Sting has always snapshot and ticked on duration after reapplication. Upon testing Piercing Shots and Serpent Sting, I can confirm, Piercing Shots is Not applying new aura's to stack with the current aura ie 161 dmg ticks second piercing shots adds 251 251 then back down to new dot 90 with remaining duration. Serpent Sting snapshot dot dmg is also reapplied when a new application is produced from Chimera shot. It should snapshot the same serpent sting from the original cast. It is not here on whitemane.

**Comment by haephaistoss** [comment] 2024-07-11 06:55
Stacking mechanics need further investigation - but ignite which behaves in a similar manner contradicts your statement.

It is the main dmg of a fire mage, using the same idea as deep wounds, Piercing shots, righteous vengeance, and currently as a fire mage with enough crit I can push through a fight with virtually no ignite DMG, because I can stack kt infinitely, never having it tick and deal any DMG.

Some info from an actual expert of the mage class would be nice as I'm playing mostly melees.

Retail testing so far proves what I have stated

**Comment by UltraNix** [comment] 2024-07-11 13:33
About snapshoting - it's not a bug (at least on wotlk).

**Comment by UltraNix** [comment] 2024-07-11 13:53
`(All DoTs seem to keep both the caster and target in combat.)`
Tested with Moonfire against other player: application does put you in combat (it's normal spellcast - not a bug), but damage from DoT does not - also not a bug.
Against mob: every damage (event DoT) builds threat on your target, thus keeping you in combat - also not a bug.

**Comment by UltraNix** [comment] 2024-07-11 14:25
About roll timer mechanic: https://wowpedia.fandom.com/wiki/Damage_over_Time
`Also as of patch 4.0.1, DoTs no longer can be 'clipped'. Previously, if a DoT was refreshed before it had expired, the tick timer was reset, causing a delay of up to double the normal time between ticks between the last tick that occurred and the first tick of the refreshed DoT.`

**Comment by UltraNix** [comment] 2024-07-11 14:27
Please remember - classic Wotlk has many changes from other patches (after original 3.3.5 wotlk) and often cannot be reference for us.

**Comment by slicplaya** [comment] 2024-07-12 06:40
Chimera Shot is supposed to "refresh" the sting on the target, not reapply it, as the tooltip states.  It's supposed to Snapshot, and it's not. Piercing Shots is reapplying a new dot, instead of stacking separate duration stacks increasing and decreasing the damage as new aura's of the talent are applied/drop off. Test it.

**Comment by UltraNix** [comment] 2024-07-12 07:17
I was referring to the issues reported on this topic as a general ones.
 I will look at these @slicplaya

**Comment by haephaistoss** [comment] 2024-07-12 07:51
That's why I was referring to some dots, not all - as I know there were some that behaved this way, and others that didn't.

Ignite is one I kinda see illogical to work this way, as it basically punishes you to have more crit, rendering your main DMG source practially to deal 0 dmg as you are approaching your ideal stat composition ( 100 % crit).

That doesn't make sense.

Also seal of corruption: with every auto getting refreshed, basically the tick DMG would be clipped to nothing, the dot being totally useless.

I strongly think that dots that need to be applied by actually Casting a spell worked by clipping, corruption for sire, and unstable affliction for sure, even living bomb.

And dots that stack, and or happen through not direct means have a rolling timer.

I may be wrong here, but think about it.

I'll try to look through some old raid videos finding a logic here once I'm back home next week.

If anybody has some solid idea please share

**Comment by haephaistoss** [comment] 2024-07-12 07:54
Refreshing and reapplying are indeed not the same thing.

For viper sting and corruption through Shadow Bolt I know the % modifiers should be kept through refreshing, but the AP should be recalculated in both cases.

Of reapplying (=cast again) everything should be recalculated.
DK diseases are a totally different beast, hailing from a different era of game design.

**Comment by UltraNix** [comment] 2024-07-12 16:00
About Seal of Corruption/Vengeance - damage modiers (%) are calculated correctly on every refresh/apply. Rolling timer will be fixed.

**Comment by haephaistoss** [comment] 2024-07-12 16:14
@UltraNix is it possible to add a buff to the PTR that allows the player to have 100% crit chance? So we can test the stacking stuff?

Maybe through an npc dialog or something

Or enable .mod crit x?

**Comment by UltraNix** [comment] 2024-07-12 16:31
@haephaistoss I believe on gmisland is everything you need.

**Comment by UltraNix** [comment] 2024-07-12 18:50
Tested Piercing Shots and works okay - it does cumulate damage.
![image](https://github.com/user-attachments/assets/82c69c91-6532-4b32-8426-a7cbe861668f)

First Steady Shot is 468. Piercing Shots takes 30% of it - we have 140. Now divided by 8 ticks -> it's ~17 per tick (as you can see).
Second Steady Shot is 476. Again 30% from it is 142.
Now - 5 ticks already gone, so we have only 3 ticks in our bank from the 1. DoT - 3 * 17 --> 51. Now divide that by 8 and we have ~6. So the new DoT will appear with tick about 23 (142 / 8 + 6).

**Comment by slicplaya** [comment] 2024-07-13 00:46
Great work here.

**Comment by Manpower99** [comment] 2024-07-13 01:17
IAuthor: Ultranix
Message: Core/Spells: Blood Plague and Frost Fever should not clip.
trying to understand what changed here, because from what i know dot clipping should be a thing as this isnt cataclysm+

**Comment by UltraNix** [comment] 2024-07-13 05:35
@Manpower99 In general - yes. But there are some expcetions, when they are triggered by other spells and thus you have no control on refreshing. Unless you can give me some sources I'm wrong about it.

**Comment by UltraNix** [comment] 2024-07-13 06:01
Okay - there are some expections, but DK diseases are not among them.
https://www.mmo-champion.com/threads/743510-Clipping-diseases
Another one bites the dust...
@Thanks @Manpower99 
@haephaistoss There is nothing wrong about DK diseases.
Guys - no more fixes without proofs.

**Comment by slicplaya** [comment] 2024-07-13 06:08
From a warmane source: The only buffs that Serpent Sting snapshots that are preserved through being refreshed with Chimera Shot are percentage-based damage increasing modifiers. Stuff like BQL's bite, your 2p t10 proc, Tricks of the Trade, etc. Your AP is recalculated when you refresh it with Chimera Shot, so the only buffs you need to look out for are buffs like the aforementioned ones.

**Comment by Apakalipsis1992** [comment] 2024-07-13 07:56
> In my recent testing DoTs seem to behave in an unintended manner. The issue seems to be global, that's why I'm creating this post:
> 
> (All DoTs seem to keep both the caster and target in combat.) All DoTs seem to deal dmg only if the tick period has elapsed since reapplication instead of the last tick in case of reapplication. (They all seem to be snapshotting AP / SP, even the ones that should not.)
> 
> DoTs I tested and found to be wrong:
> 
> Seal of Corruption Blood Plague Frost Fever Ignite (Fire mage) Serpent Sting Righteous Vengeance Piercing Shots
> 
> **How to reproduce:**
> 
> **How it should work:** As you can see below from a screenshot of my combatlog on retail classic ptr, the reapplication of the DoT shouldn't interfere with the tick period at all in most cases. Currently it does. I can keep reapplying the DoT for hours and deal 0 dmg.
> 
> Testing on Retail Test server Today:

Dk's dots only had snapshot in early versions of og wotlk and this was the reason for using the glyph of disease but later this was changed and diseases began to have dynamic damage changes. If suddenly the dk loses the strength buff during the action of diseases, then with the next tick the diseases become weaker.

**Comment by Apakalipsis1992** [comment] 2024-07-13 08:03
Part of an article from Elitistjerks about Udk.
It's important to note that as of patch 3.3.2, Glyph of Disease will no longer cause Pestilence to roll the AP value present when you applied diseases. Instead, whenever you case Pestilence to refresh them, diseases will look at your current value of AP (and then use that number until you cast Pestilence again). As such, one doesn't have to worry about lining up trinket procs at the start of the encounter. This makes GoD non-competitive for a single target, but still a must for a multiple target encounter.

**Comment by haephaistoss** [comment] 2024-07-13 08:22
> > In my recent testing DoTs seem to behave in an unintended manner. The issue seems to be global, that's why I'm creating this post:
> > 
> > (All DoTs seem to keep both the caster and target in combat.) All DoTs seem to deal dmg only if the tick period has elapsed since reapplication instead of the last tick in case of reapplication. (They all seem to be snapshotting AP / SP, even the ones that should not.)
> > 
> > DoTs I tested and found to be wrong:
> > 
> > Seal of Corruption Blood Plague Frost Fever Ignite (Fire mage) Serpent Sting Righteous Vengeance Piercing Shots
> > 
> > **How to reproduce:**
> > 
> > **How it should work:** As you can see below from a screenshot of my combatlog on retail classic ptr, the reapplication of the DoT shouldn't interfere with the tick period at all in most cases. Currently it does. I can keep reapplying the DoT for hours and deal 0 dmg.
> > 
> > Testing on Retail Test server Today:
> 
> Dk's dots only had snapshot in early versions of og wotlk and this was the reason for using the glyph of disease but later this was changed and diseases began to have dynamic damage changes. If suddenly the dk loses the strength buff during the action of diseases, then with the next tick the diseases become weaker.


This is the behavior I was trying to convey, as I remembered them working like this.

I wanted to open up conversation, and this is exactly what happened, so thank you everyone present here to help fix stuff, we're doing great 🫡

**Comment by scrublama** [comment] 2024-07-13 11:24
> @UltraNix is it possible to add a buff to the PTR that allows the player to have 100% crit chance? So we can test the stacking stuff?
> 
> Maybe through an npc dialog or something
> 
> Or enable .mod crit x?

.additem 18970

**Comment by haephaistoss** [comment] 2024-07-13 11:32
forgot about these, thanks ❤️

**Comment by UltraNix** [comment] 2024-07-24 12:21
Fixed.

**Closed by UltraNix** 2024-07-24 12:21 UTC
Labels: Need More Info from Reporter, High Prio
