### ISSUE TITLE
[CORE / CLIENT?] Compare Achievements Statistics Tab not Working

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1889] opened 2024-09-14 19:35 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Compare Achievements -> Statistics tab doesn't show anything or inspected players. Running Whitemane patch 3.3

![image](https://github.com/user-attachments/assets/bc0150cc-3f6a-46e4-be7b-08a69a5da5c3)

**How to reproduce:**

**How it should work:** it should show stuff

**Database links:**

**Comment by Aeradel** [comment] 2024-09-14 19:40
i was not able to reproduce this. make sure you're using the most recent client and most recent patch  - available on our Discord by typing !client and !patch.

If you install the newer client, the patch is already on it :+1:

**Comment by haephaistoss** [comment] 2024-09-22 15:41
tried yesterday, and it's still not working for me
Weird...
I'm copying over my wtf folder from the previous installation to keep my settings and stuff

**Comment by Piootrek** [comment] 2024-09-23 11:16
Fixed, I will close this issue once the fix comes live.

**Closed** 2024-10-02 12:06 UTC
Labels: Medium Prio
