### ISSUE TITLE
Warrior Deep Wounds is doing way more damage then it should

### ISSUE THREAD

**Issue by jonathansbb** [gamefreedomgit/Frostmourne#1761] opened 2024-09-03 11:46 UTC
**Description:**
Warriors deep wounds is doing too much damage. This coupled with how well warriors scale with gear will make warriors extremely overpowered. Right now we have a warrior doing over 10k dps on Pathcwerk with a bad timer, 3rd place across all classes. This is absolutely absurd considering how good they become end Ulduar/TOGC. Some of this dps is partly because of the buff that the sunlute weap just got as well, which also is absurd (its way too good), but thats another matter.

**How to reproduce:**
Equip sunlute, raid buffs and blast.

**How it should work:**
Using Patchwerk as an example as its the best for testing pure dps:
1. Wotlk Classic: Avg. deep wounds tic on number 1 parse arms warrior on patchwerk was 1,9k tick 
2. Whitemane: Avg. deep wounds tic on number 1 parse arms warrior on patchwerk is 3.3k per tick
--> Worth mentioning that this warrior has hysteria 23% of the fight meaning his damage should theoritcally be somewhat higher on deep wounds. But nowhere near as much damage as this.

**UPDATE 1:** check bug report for further explanation: [Deep Wounds and Trauma #1378](https://github.com/gamefreedomgit/Frostmourne/issues/1378#issue-2410041583)

**UPDATE 2:** Herp Derp has made a video with undeniable proof basically. Have a look:
https://youtu.be/hoF0KpGzzf4

See attached logs

**Database links:**
1. https://uwu-logs.xyz/reports/24-09-02--17-57--Slumberseed--Whitemane-Frostmourne/player/Pumper/?boss=patchwerk
2. https://classic.warcraftlogs.com/reports/yxM3chpjNmaZ1wWr#fight=14&type=damage-done&source=16

**Comment by AlucardHellsingChapel** [comment] 2024-09-03 12:11
i love comparing betreyer to sunlute that is better than it and has also a proc that can stack deepwounds aswell

**Comment by jonathansbb** [comment] 2024-09-03 12:14
> i love comparing betreyer to sunlute that is better than it and has also a proc that can stack deepwounds aswell

You can cope all you want mister. Fact is warriors shouldnt be doing this kind of damage this early. Will be very unbalanced when warriors start getting gear in ulduar etc.

**Comment by AlucardHellsingChapel** [comment] 2024-09-03 12:15
> > i love comparing betreyer to sunlute that is better than it and has also a proc that can stack deepwounds aswell
> 
> You can cope all you want mister. Fact is warriors shouldnt be doing this kind of damage this early. Will be very unbalanced when warriors start getting gear in ulduar etc.

shouldnt be doing that kind of damage meanwhile classic wotlk https://youtu.be/NSxRJTOiQ50?t=63

**Comment by vedude** [comment] 2024-09-03 12:16
You do realize that the sun lute will be replaced in TOC? It's an early boost that will even be replaced by Vesax heroic sword.

People doesn't seem to realize that it scales fine and yes more due to sun lute weapon damage and proc which is making the munching climb faster to it's peak.

**Comment by Manpower99** [comment] 2024-09-03 12:17
> You do realize that the sun lute will be replaced in TOC? It's an early boost that will even be replaced by Vesax heroic sword.
> 
> People doesn't seem to realize that it scales fine and yes more due to sun lute weapon damage and proc which is making the munching climb faster to it's peak.

Make the Munching climb faster? i don't think you know what munching is.

**Comment by Manpower99** [comment] 2024-09-03 12:25
> You can cope all you want mister. Fact is warriors shouldnt be doing this kind of damage this early. Will be very unbalanced when warriors start getting gear in ulduar etc.

Fully agreed, hard scaling classes like feral and warrior are weaker than the rest this early on for a reason. they scale immensely with gear and these custom changes and bugs are not beneficial but rather a failed attempt at rebalancing the game. 
this is why there is a massive desparity between high end warriors and mid warriors simply due to the gear requirement and also the minmaxing.
it's like imagine looking at fire mages in cata classic rn and nerfing it because they're broken in the first tier of using the final patch of the expansion class Balance. it is pure non-sense.
There is both scaling related to gear, encounters being different and favoring certain specs and classes, and also tier sets.
Regardless it is fully confirmed that https://github.com/gamefreedomgit/Frostmourne/issues/1761 bug got reverted due to some people crying in discord despite no evidence being shown or a bug report being made.

**Comment by RealDerpyDude** [comment] 2024-09-03 12:31
> You do realize that the sun lute will be replaced in TOC? It's an early boost that will even be replaced by Vesax heroic sword.
> 
> People doesn't seem to realize that it scales fine and yes more due to sun lute weapon damage and proc which is making the munching climb faster to it's peak.

Sunlute in its current state will not be replaced in uld at all, plus the bigger issue is deep wounds benefitting twice from mangle / trauma. On a sidenote, 1 classic log out of thousands from someone getting giga rng should not be the benchmark when it comes to warrior balancing.

**Comment by Manpower99** [comment] 2024-09-03 12:35
> > You do realize that the sun lute will be replaced in TOC? It's an early boost that will even be replaced by Vesax heroic sword.
> > People doesn't seem to realize that it scales fine and yes more due to sun lute weapon damage and proc which is making the munching climb faster to it's peak.
> 
> Sunlute in its current state will not be replaced in uld at all, plus the bigger issue is deep wounds benefitting twice from mangle / trauma. On a sidenote, 1 classic log out of thousands from someone getting giga rng should not be the benchmark when it comes to warrior balancing.

![image](https://github.com/user-attachments/assets/2040317d-fb73-467e-b621-956d3f7a24d6)
A point well made.

**Comment by crabcakeowo** [comment] 2024-09-03 12:38
Replaced by Vezax heroic sword? No it does not get replaced by it as it is currently better, that's one gameplay design issue here for a legendary that has almost no real requirements to obtain, regardless it doesn't make sense for people to go back to do T7 raids during T8 and that is just a design flaw of the sword. 

Anyhow, that shouldn't be discussed here as the issue in question is deep wounds doing too much damage at the moment.

Also to anyone debating that warriors are doing correct damage at the moment.
Just to pull up some numbers from WOTLK Classic phase 2 Patchwerk (Sort of test dummy boss).
Top1 Fury Warrior on phase 2 (ilvl 252 hm items)
https://classic.warcraftlogs.com/reports/qtHB71N4DP8ThQfW#fight=281&type=damage-done&source=825
791k total damage dealt (1:20 kill time)
9671 dps
124.8k damage from deep wounds (amounting to 15.7% of total damage dealt)

Top1 Arms Warrior on phase 2 (ilvl 252 hm items)
https://classic.warcraftlogs.com/reports/vrX1WVqPMCbYRcGL#fight=14&type=damage-done&source=16
1.12m total damage dealt (2:13 kill time)
8295 dps
210.8k damage from deep wounds (amounting to 18.9% of total damage dealt)

So, what some of you are saying is that currently we should be doing more DPS than phase 2 BiS warriors?

Keep in mind that the ilvl jump from 213s to 252s is actually bigger than you think.

**Comment by Nihaobeachez** [comment] 2024-09-04 09:58
Their revert is based on this log 
![image](https://github.com/user-attachments/assets/17c7b2b2-4903-4ad0-b0bf-2ba9f9126bce)
which should be more than clear that its bugged, if you just look at the uptime of deep wounds. 30 ticks total, first 15 seconds no tick at all? then random drops? but 96% uptime? you dont need to be professor to see that its false data and should NOT be the base of how its supposed to work. 
meanwhile every other log looks like this 
![image](https://github.com/user-attachments/assets/85e2553c-90ab-4242-b05e-d2bd83c126b4)
with the same amount of uptime. 

Radeghost gave us the code of Deep Wounds https://pastebin.com/raw/bMVbHfVr, while im smart enough to realize that its bugged in current state, im not smart enough to do anything with the code so feel free to do some digging

**Comment by AlucardHellsingChapel** [comment] 2024-09-04 10:00
> Their revert is based on this log ![image](https://private-user-images.githubusercontent.com/96308500/364323792-17c7b2b2-4903-4ad0-b0bf-2ba9f9126bce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDQyNDIsIm5iZiI6MTcyNTQ0Mzk0MiwicGF0aCI6Ii85NjMwODUwMC8zNjQzMjM3OTItMTdjN2IyYjItNDkwMy00YWQwLWIwYmYtMmJhOWY5MTI2YmNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA5NTkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MWUxNzZkNjE3OGU5MzYwMzMyN2VhODg3NDNmYjNkMTAyMzRlYTFmMjJjZTIwMzQwZmJkMmU4MmYxYTJlMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.14VedHNyYGQwl6cY1YvYtAA62btcsz0tJDUAgmo1jjs) which should be more than clear that its bugged, if you just look at the uptime of deep wounds. 30 ticks total, first 15 seconds no tick at all? then random drops? but 96% uptime? you dont need to be professor to see that its false data and should NOT be the base of how its supposed to work. meanwhile every other log looks like this ![image](https://private-user-images.githubusercontent.com/96308500/364326909-85e2553c-90ab-4242-b05e-d2bd83c126b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDQyNDIsIm5iZiI6MTcyNTQ0Mzk0MiwicGF0aCI6Ii85NjMwODUwMC8zNjQzMjY5MDktODVlMjU1M2MtOTBhYi00MjQyLWIwNWUtZDJiZDgzYzEyNmI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA5NTkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2YjMwMzgyYmU3MzAxNDlhOWJmZjIzYWU0YjhlOTE0M2MwNGQ0NDZlYzU3NjMwYTQzYWY2ODMwMWU5ZDk2NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PwyyYrHRR5SG276hEUe2BGi2BXliq2pLQC4PIBvkFEY) with the same amount of uptime.
> 
> Radeghost gave us the code of Deep Wounds https://pastebin.com/raw/bMVbHfVr, while im smart enough to realize that its bugged in current state, im not smart enough to do anything with the code so feel free to do some digging

no the revert is based that after the change deep wounds was doing even less than supposed xD

**Comment by AlucardHellsingChapel** [comment] 2024-09-04 10:01
![image](https://github.com/user-attachments/assets/48965dd8-89c4-4247-aa12-0b6836c42576)

**Comment by Nihaobeachez** [comment] 2024-09-04 10:08
And the Damage "its supposed to do" is based on the log ive posted, he literally said it himself.
![image](https://github.com/user-attachments/assets/9b8f8d1a-ba55-4e6d-be9f-014912c303cf)

**Comment by danniellos94** [comment] 2024-09-04 10:28
Maybe this can help https://www.wowhead.com/wotlk/news/wrath-classic-hotfixes-october-14-deep-wounds-and-fiery-weapon-329368
So in wotlk all crits could proc the deep wounds so some warrior was using flame caps, fiery weapon even low lvl gloves with fire damage and enchant to stack deep wounds to have bigger hits. I'm not sure if that's the reason but might be worth checking out.

**Comment by jonathansbb** [comment] 2024-09-04 10:36
How about this. Look at the DPS contribution. 
1. https://uwu-logs.xyz/reports/24-09-02--17-57--Slumberseed--Whitemane-Frostmourne/player/Pumper/?boss=patchwerk
-> Dps contribution is 267k(Damage)/126s (lenght of fight) = 2119 DPS

2. https://classic.warcraftlogs.com/reports/mVDMnc1jQK42CRvJ#fight=11&type=damage-done&source=25&ability=12721
-> Dps contribution is 123.1k/87s = 1406 DPS

Most warriors are closer to 1k dps from deep wounds. Also the above timer is 39 seconds faster, which obviously increases uptime on both Lust and Death Wish

**Comment by Karsenity** [comment] 2024-09-04 10:39
> Maybe this can help https://www.wowhead.com/wotlk/news/wrath-classic-hotfixes-october-14-deep-wounds-and-fiery-weapon-329368
> 
> So in wotlk all crits could proc the deep wounds so some warrior was using flame caps, fiery weapon even low lvl gloves with fire damage and enchant to stack deep wounds to have bigger hits. I'm not sure if that's the reason but might be worth checking out.

This was fixed in wotlk classic p1, so the date would be needed to determine if this is the case.

But on the same vein... I noticed nobody brought up the fact that munching was fixed in wotlk classic. Meaning deep wounds should be higher on wotlk classic because they're gaining additional hits.

**Comment by AlucardHellsingChapel** [comment] 2024-09-04 10:45
굿바이 낙스
Created by InNoX on Sat Jan 14 2023 log date 
Wrath Classic Hotfixes October 14 - Deep Wounds and Fiery Weapon
[WRATH](https://www.wowhead.com/wotlk/news?type=17) POSTED 2022/10/14 AT 5:51 PM BY [ROKMAN](https://www.wowhead.com/wotlk/news?user=Rokman) bug fix date

**Comment by crabcakeowo** [comment] 2024-09-04 10:48
You can't be serious right? There's absolutely no way deep wounds ticked for 30 times that fight when it ticks once per second.

**Comment by danniellos94** [comment] 2024-09-04 10:51
> > Maybe this can help https://www.wowhead.com/wotlk/news/wrath-classic-hotfixes-october-14-deep-wounds-and-fiery-weapon-329368
> > So in wotlk all crits could proc the deep wounds so some warrior was using flame caps, fiery weapon even low lvl gloves with fire damage and enchant to stack deep wounds to have bigger hits. I'm not sure if that's the reason but might be worth checking out.
> 
> This was fixed in wotlk classic p1, so the date would be needed to determine if this is the case.
> 
> But on the same vein... I noticed nobody brought up the fact that munching was fixed in wotlk classic. Meaning deep wounds should be higher on wotlk classic because they're gaining additional hits.

Yea I agree munching sucks and should be fixed imo, even the thing that you need to desync weapons is lame just pointing what could be wrong because I know private server players use flame cap a lot.

**Comment by Karsenity** [comment] 2024-09-04 10:56
> > > Maybe this can help https://www.wowhead.com/wotlk/news/wrath-classic-hotfixes-october-14-deep-wounds-and-fiery-weapon-329368
> 
> > > So in wotlk all crits could proc the deep wounds so some warrior was using flame caps, fiery weapon even low lvl gloves with fire damage and enchant to stack deep wounds to have bigger hits. I'm not sure if that's the reason but might be worth checking out.
> 
> > 
> 
> > This was fixed in wotlk classic p1, so the date would be needed to determine if this is the case.
> 
> > 
> 
> > But on the same vein... I noticed nobody brought up the fact that munching was fixed in wotlk classic. Meaning deep wounds should be higher on wotlk classic because they're gaining additional hits.
> 
> 
> 
> Yea I agree munching sucks and should be fixed imo, even the thing that you need to desync weapons is lame just pointing what could be wrong because I know private server players use flame cap a lot.

I'm not saying munching sucks or needs to be fixed. I'm just pointing out that since retail logs don't have it, we lose procs of deep wounds by comparison. Which means we SHOULD be lower than a wotlk classic log, assuming same weapon is used and no flamecaps or fiery plate gauntlets, which you can check for in the uwulogs damage breakdown.

**Comment by crabcakeowo** [comment] 2024-09-04 11:11
Good point about the munching, it's probably what's making deep wounds doing less damage than intended, however double dipping into the talent was never a thing and never will be, how this got through to implementation is beyond me.

**Comment by RealDerpyDude** [comment] 2024-09-04 13:01
https://youtu.be/hoF0KpGzzf4

**Comment by Manpower99** [comment] 2024-09-04 13:13
> https://youtu.be/hoF0KpGzzf4

Ultimate proof that https://github.com/gamefreedomgit/Frostmourne/issues/1378 got reverted at the request of certain individuals who were unhappy with their performance on logs.

**Comment by Manpower99** [comment] 2024-09-04 13:45
As for those claiming in the discord that it was "reduced by armor".
Unless the core function of bleeds is reducable by armor then all bleeds would have been reduced by armor. of course no bleed should be reduced by armor, which is obviously bogus.
you can check every bleed in logs the damage remains the same except deep wounds, this is just an intentional bug that has existed since sunwell times to improve a warrior class dmg.

**Comment by Piootrek** [comment] 2024-09-04 14:39
Fixed double dipping

**Comment by AlucardHellsingChapel** [comment] 2024-09-04 15:16
also it would be good to look more into this (trinitycore) 
https://github.com/TrinityCore/TrinityCore/issues/1188
https://gist.github.com/tobmaps/1088109

**Comment by husker3011** [comment] 2024-09-04 16:41
Very sloppy info warning.

I dont know if this is a bugged interaction or not, few weeks back testing with a heroic throw, no debuffs, tricks increased deep wounds by 15% but hysteria only increased deep wounds by 11% (instead of 20%), indicating there is something causing dimishing returns on "increased physical damage" by around 100% or there is some physical damage multiplier applying to deep wounds I'm not familiar with.

Could be nothing tho.

**Closed** 2024-09-11 07:56 UTC
Labels: High Prio
