### ISSUE TITLE
[ToGC] Anub block value bug

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#2412] opened 2024-11-22 11:54 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Each stack of expose weakness increases your block value significantly, making you end up with about 8k block value at 9 stacks, or up to 17k if using block gear, allowing adds to be almost ignored even though block tanking in the typical sense is impossible. It seems to be a percentage increase, since gaining the 450 block value effect from your libram increases block value by almost 3000 as you can see in the screenshot.

**How to reproduce:**
Play prot paladin or prot warrior and let nerubian burrowers hit you

**How it should work:**
Expose weakness should increase your physical damage taken and not have any other effects.

PS: The adds seem to hit extremely hard (16k each) without this bug, so the thought crossed my mind that it's been added to make them Tankable without having to use the block tank strategy. If that is the case, I don't think the solution works because warriors will be unbalanced and then you're back at square one except the situation is even worse than just regular block tanking due to only warriors being good.

**Database links:**
https://www.wowhead.com/wotlk/spell=67721/expose-weakness
![image](https://github.com/user-attachments/assets/a4f04c00-b3a8-4b80-8589-d33e4d1fd47a)
![image](https://github.com/user-attachments/assets/281f95e3-a201-4649-9c23-66d60212b71e)

**Comment by Piootrek** [comment] 2024-11-22 12:30
I can't reproduce this. Can you make a video of this bug with shown equipped items and talents?

**Comment by NickZedd** [comment] 2024-11-22 13:36
Yeah, here you go.
https://youtu.be/5u6R_WG6ufY

**Comment by Piootrek** [comment] 2024-11-22 15:37
Fixed, I will close this issue once the fix comes live.

**Closed** 2024-11-25 09:45 UTC
Labels: High Prio, PTR
