### ISSUE TITLE
Malygos couple of recent issues

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1628] opened 2024-08-19 12:39 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Recently **Malygos** had some new issues introduced to him or that i didn't notice during **Beta** :

 ~~1. Right after vortex ends and players are falling to the ground if you use movement displacement such as **Demonic Circle Teleport** or **Blink** you have a very high chance of falling under the map.~~ casting them is no longer possible now.
 Edit : using blink right after Vortex ends kills the mage by falling through texture.

2. **Sparks** are desyncing in multiple ways, you could get the _custom_ debuff **Chilled to the Bone** while not standing in it or at the edge of it, despite not benefitting from the **blizzlike Spark debuff** that amplifies your damage. some players have also mentioned that you could sit on it and not get **Chilled of the Bone**. in either ways it is quite annoying and super noticable.

3. Sometimes the **Spark** position moves after it dies, very noticable as a DK if you grip it to a position and it dies, a second later it will move from that position.

4. This might be related to players addons but i've done over 50+ pugs of EoE 25 and theres always a couple of people in each raid who's **Vehicle ui** bugs and their spells are not usable unless they reload midfight which is usually fatal. can't say for certain what is causing this but it does happen consistently so maybe the fix could be server sided.

Edit: Noticed that 4. happens alot to ppl who are on the disk and then phase 3 (vehicle/dragon phase ) starts. the same players who consistently get this bug if they no longer jump on a disk prior to P3 the bug doesn't happen to them. unsure if fix could be handled server side.

**Database links:**

**Comment by Riztazz** [comment] 2024-09-20 13:20
Can i get a video of the 4? How it looks from player perspective? I cannot reproduce this :/
Fixed the rest

**Comment by Riztazz** [comment] 2024-09-23 08:53
I'll close this as most is fixed, please open another issue for (4) if you get a video of it please, i need some clue to continue, no idea how to reproduce this

**Closed by Riztazz** 2024-09-23 08:53 UTC
Labels: Medium Prio

**Comment by Manpower99** [comment] 2024-09-23 11:15
> I'll close this as most is fixed, please open another issue for (4) if you get a video of it please, i need some clue to continue, no idea how to reproduce this

yeah i will, will be a bit slow on it since i have to join a pug to try and reproduce it.
