### ISSUE TITLE
Can't enter Zul'Gurub the lvl 60 raid

### ISSUE THREAD

**Issue by Mixetaa** [gamefreedomgit/Frostmourne#1906] opened 2024-09-16 20:16 UTC
**Description:** Can't enter Zul'Gurub raid, it says "Instance is closed" even tho my raid dificulty is set to 10 or 25 man normal.
![image](https://github.com/user-attachments/assets/19e35405-d35b-447a-9ccd-e7537516f6b8)

**How to reproduce:** Go to the entrance of Zul'Gurub, be in a raid group, set difficulty to either 10 or 25 man normal and try to enter the raid.

**How it should work:** You should be able to enter the raid if the difficulty is set to normal

**Comment by Manpower99** [comment] 2024-09-16 20:41
It's been closed due to server crash issue that happened about two days ago, still unfixed it seems.

**Comment by Aeradel** [comment] 2024-09-17 04:54
This is not a bug and the instance is intentionally closed, as Manpower99 says.

We are currently working on testing the fix implemented to ensure stability and the instance will be opened soon.

**Comment by Riztazz** [comment] 2024-09-17 10:06
Lemme know if it works;p

**Comment by Aeradel** [comment] 2024-09-17 23:45
> Lemme know if it works;p

We can't test it because it's a closed instance :laughing:

**Closed** 2024-10-08 09:52 UTC
Labels: High Prio
