### ISSUE TITLE
Stun delay not fixed, especially in pvp

### ISSUE THREAD

**Issue by radeghostmademedoit** [gamefreedomgit/Frostmourne#880] opened 2024-06-12 16:25 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
If you stun someone with cheap shot he can still cast something instant. This should not be possible and makes rogues very bad in pvp.
Even between stuns people can cast something. Cheap shot in to kidney shot while cheap is still on and they can cast something in between.

**How to reproduce:**
Cheap shot someone and let him use an instant cast on you

**How it should work:**
Players should not be able to react to a cheap shot. Haven't tested it in the world yet but probably is also still a problem

**Database links:**

**Comment by UltraNix** [comment] 2024-06-12 17:15
You know there is a spell batching?

**Comment by radeghostmademedoit** [comment] 2024-06-12 19:21
I don't think spell batching should work like that. I've never seen anything like that before.

and especially this doesn't explain why someone could cast something when 2 stuns overlap

**Comment by FlinkSkink** [comment] 2024-06-21 11:51
This is how it was on retail for the longest time, but no private server has ever had this issue before. 2 players' ping can be <50 but the effective latency can be several seconds. I have this same issue, and it's a pretty broad issue. I can use cheap shot on someone, and they will continue to run out of my attack range while being stunned. Applying slows and dealing damage on players also have a massive delay. I can be within <1 yard (melee range is 5 yards) of another player, and will get the out of reach error. The delay is so severe that players are not at all where they appear to be. All of this applies to most player enemies, but there are a small number of players that dont have as much delay between me and them, as others have.
It's a blizzlike thing, but effectively playing with several seconds of delay is completely unbearable, and if this kind of spell batching isnt fixed/removed, PvP will not be enjoyable for anyone who is really into it. I see people complain about this in worldchat all the time. 
It is blizzlike, but very much undesirable, and should not be necessary for the server to handle stress, especially when the view distance is as low as it is, compared to other servers.

**Comment by madihaz** [comment] 2024-06-24 19:50
This can be reproduced 100% on Ymirheim Chosen Warrior in Icecrown. Even if you Sap the mob first.
The initial `Jump Attack` and `Cleave` you could argue could be because the Stealth drops before Cheap Shot is applied, at least it appears that way in the combat log, but I guess it's batched anyway.
Interestingly the mob casts Bloodthirst and Cleave later on still during Cheap Shot before it fades. Are those abilities just allowed to be cast by the mob while stunned or something different is at play here?

```
6/24 21:39:12.541  SPELL_CAST_SUCCESS,0x00000000000026BE,"Ihaz",0x511,0x0000000000000000,nil,0x80000000,1784,"Stealth",0x1
6/24 21:39:12.541  SPELL_AURA_APPLIED,0x00000000000026BE,"Ihaz",0x511,0x00000000000026BE,"Ihaz",0x511,1784,"Stealth",0x1,BUFF
6/24 21:39:12.541  SPELL_AURA_APPLIED,0x00000000000026BE,"Ihaz",0x511,0x00000000000026BE,"Ihaz",0x511,58427,"Overkill",0x1,BUFF
6/24 21:39:13.370  SPELL_CAST_SUCCESS,0x00000000000026BE,"Ihaz",0x511,0x0000000000000000,nil,0x80000000,1725,"Distract",0x1
6/24 21:39:15.405  SPELL_CAST_FAILED,0x00000000000026BE,"Ihaz",0x511,0x0000000000000000,nil,0x80000000,51724,"Sap",0x1,"Out of range"
6/24 21:39:16.806  SPELL_CAST_SUCCESS,0x00000000000026BE,"Ihaz",0x511,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,51724,"Sap",0x1
6/24 21:39:16.905  SPELL_AURA_APPLIED,0x00000000000026BE,"Ihaz",0x511,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,51724,"Sap",0x1,DEBUFF
6/24 21:39:22.525  SPELL_AURA_REMOVED,0x00000000000026BE,"Ihaz",0x511,0x00000000000026BE,"Ihaz",0x511,1784,"Stealth",0x1,BUFF
6/24 21:39:22.525  SPELL_CAST_SUCCESS,0x00000000000026BE,"Ihaz",0x511,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,1833,"Cheap Shot",0x1
6/24 21:39:22.525  SPELL_CAST_SUCCESS,0x00000000000026BE,"Ihaz",0x511,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,57965,"Instant Poison IX",0x8
6/24 21:39:22.540  SPELL_DAMAGE,0x00000000000026BE,"Ihaz",0x511,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,57965,"Instant Poison IX",0x8,846,0,8,0,0,0,nil,nil,nil
6/24 21:39:22.540  SPELL_AURA_REMOVED,0x00000000000026BE,"Ihaz",0x511,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,51724,"Sap",0x1,DEBUFF
6/24 21:39:22.540  SPELL_CAST_SUCCESS,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,0x00000000000026BE,"Ihaz",0x511,61227,"Jump Attack",0x1
6/24 21:39:22.540  SPELL_AURA_REFRESH,0x00000000000026BE,"Ihaz",0x511,0x00000000000026BE,"Ihaz",0x511,58427,"Overkill",0x1,BUFF
6/24 21:39:22.575  SPELL_CAST_FAILED,0x00000000000026BE,"Ihaz",0x511,0x0000000000000000,nil,0x80000000,48666,"Mutilate",0x1,"Not yet recovered"
6/24 21:39:22.583  SWING_DAMAGE,0x00000000000026BE,"Ihaz",0x511,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,448,0,1,0,0,0,nil,nil,nil
6/24 21:39:22.609  SPELL_AURA_APPLIED,0x00000000000026BE,"Ihaz",0x511,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,1833,"Cheap Shot",0x1,DEBUFF
6/24 21:39:22.925  SPELL_DAMAGE,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,0x00000000000026BE,"Ihaz",0x511,61227,"Jump Attack",0x1,619,0,1,0,0,0,nil,nil,nil
6/24 21:39:23.259  SPELL_CAST_SUCCESS,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,0x00000000000026BE,"Ihaz",0x511,15496,"Cleave",0x1
6/24 21:39:23.259  SPELL_DAMAGE,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,0x00000000000026BE,"Ihaz",0x511,15496,"Cleave",0x1,466,0,1,0,0,0,nil,nil,nil
6/24 21:39:23.426  SPELL_CAST_FAILED,0x00000000000026BE,"Ihaz",0x511,0x0000000000000000,nil,0x80000000,48666,"Mutilate",0x1,"Not yet recovered"
6/24 21:39:23.559  SWING_DAMAGE,0x00000000000026BE,"Ihaz",0x511,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,453,0,1,0,0,0,1,nil,nil
6/24 21:39:23.559  SPELL_CAST_SUCCESS,0x00000000000026BE,"Ihaz",0x511,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,57970,"Deadly Poison IX",0x8
6/24 21:39:23.559  SPELL_ENERGIZE,0x00000000000026BE,"Ihaz",0x511,0x00000000000026BE,"Ihaz",0x511,51637,"Focused Attacks",0x1,2,3
6/24 21:39:23.559  SPELL_CAST_SUCCESS,0x00000000000026BE,"Ihaz",0x511,0x0000000000000000,nil,0x80000000,25733,"Unsurpassed Vigor",0x1
6/24 21:39:23.559  SPELL_HEAL,0x00000000000026BE,"Ihaz",0x511,0x00000000000026BE,"Ihaz",0x511,25733,"Unsurpassed Vigor",0x1,354,0,0,nil
6/24 21:39:23.559  SPELL_AURA_APPLIED,0x00000000000026BE,"Ihaz",0x511,0x00000000000026BE,"Ihaz",0x511,60233,"Greatness",0x2,BUFF
6/24 21:39:23.575  SPELL_AURA_APPLIED,0x00000000000026BE,"Ihaz",0x511,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,57970,"Deadly Poison IX",0x8,DEBUFF
6/24 21:39:23.643  SPELL_DAMAGE,0x00000000000026BE,"Ihaz",0x511,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,48665,"Mutilate",0x1,1905,0,1,0,0,0,1,nil,nil
6/24 21:39:23.643  SPELL_ENERGIZE,0x00000000000026BE,"Ihaz",0x511,0x00000000000026BE,"Ihaz",0x511,51637,"Focused Attacks",0x1,2,3
6/24 21:39:23.645  SPELL_CAST_SUCCESS,0x00000000000026BE,"Ihaz",0x511,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,57965,"Instant Poison IX",0x8
6/24 21:39:23.645  SPELL_DAMAGE,0x00000000000026BE,"Ihaz",0x511,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,57965,"Instant Poison IX",0x8,1024,0,8,0,0,0,nil,nil,nil
6/24 21:39:23.645  SPELL_DAMAGE,0x00000000000026BE,"Ihaz",0x511,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,48664,"Mutilate",0x1,1442,0,1,0,0,0,1,nil,nil
6/24 21:39:23.645  SPELL_ENERGIZE,0x00000000000026BE,"Ihaz",0x511,0x00000000000026BE,"Ihaz",0x511,51637,"Focused Attacks",0x1,2,3
6/24 21:39:23.645  SPELL_CAST_SUCCESS,0x00000000000026BE,"Ihaz",0x511,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,48666,"Mutilate",0x1
6/24 21:39:23.645  SPELL_AURA_APPLIED,0x00000000000026BE,"Ihaz",0x511,0x00000000000026BE,"Ihaz",0x511,60065,"Reflection of Torment",0x1,BUFF
6/24 21:39:23.725  SPELL_CAST_FAILED,0x00000000000026BE,"Ihaz",0x511,0x0000000000000000,nil,0x80000000,48666,"Mutilate",0x1,"Not yet recovered"
6/24 21:39:24.209  SWING_DAMAGE,0x00000000000026BE,"Ihaz",0x511,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,541,0,1,0,0,0,nil,nil,nil
6/24 21:39:24.342  SPELL_CAST_FAILED,0x00000000000026BE,"Ihaz",0x511,0x0000000000000000,nil,0x80000000,57993,"Envenom",0x8,"Not yet recovered"
6/24 21:39:24.476  SPELL_CAST_SUCCESS,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,0x00000000000026BE,"Ihaz",0x511,35949,"Bloodthirst",0x1
6/24 21:39:24.476  SPELL_DAMAGE,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,0x00000000000026BE,"Ihaz",0x511,35949,"Bloodthirst",0x1,376,0,1,0,0,0,nil,nil,nil
6/24 21:39:24.476  SPELL_HEAL,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,35947,"Bloodthirst",0x1,395,0,0,nil
6/24 21:39:24.609  SPELL_AURA_APPLIED,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,35948,"Bloodthirst",0x1,BUFF
6/24 21:39:24.626  SPELL_CAST_FAILED,0x00000000000026BE,"Ihaz",0x511,0x0000000000000000,nil,0x80000000,57993,"Envenom",0x8,"Not enough energy"
6/24 21:39:24.761  SWING_DAMAGE,0x00000000000026BE,"Ihaz",0x511,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,289,0,1,0,0,0,nil,nil,nil
6/24 21:39:24.761  SPELL_CAST_SUCCESS,0x00000000000026BE,"Ihaz",0x511,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,57970,"Deadly Poison IX",0x8
6/24 21:39:24.776  SPELL_CAST_FAILED,0x00000000000026BE,"Ihaz",0x511,0x0000000000000000,nil,0x80000000,57993,"Envenom",0x8,"Not enough energy"
6/24 21:39:24.810  SPELL_AURA_APPLIED_DOSE,0x00000000000026BE,"Ihaz",0x511,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,57970,"Deadly Poison IX",0x8,DEBUFF,2
6/24 21:39:25.461  SPELL_DAMAGE,0x00000000000026BE,"Ihaz",0x511,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,57993,"Envenom",0x8,3236,0,8,0,0,0,nil,nil,nil
6/24 21:39:25.461  SPELL_ENERGIZE,0x00000000000026BE,"Ihaz",0x511,0x00000000000026BE,"Ihaz",0x511,14181,"Relentless Strikes Effect",0x1,25,3
6/24 21:39:25.461  SPELL_AURA_APPLIED,0x00000000000026BE,"Ihaz",0x511,0x00000000000026BE,"Ihaz",0x511,57993,"Envenom",0x8,BUFF
6/24 21:39:25.543  SPELL_CAST_FAILED,0x00000000000026BE,"Ihaz",0x511,0x0000000000000000,nil,0x80000000,57993,"Envenom",0x8,"That ability requires combo points"
6/24 21:39:25.660  SPELL_CAST_SUCCESS,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,0x00000000000026BE,"Ihaz",0x511,15496,"Cleave",0x1
6/24 21:39:25.661  SPELL_DAMAGE,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,0x00000000000026BE,"Ihaz",0x511,15496,"Cleave",0x1,400,0,1,0,0,0,nil,nil,nil
6/24 21:39:25.661  SPELL_HEAL,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,35947,"Bloodthirst",0x1,394,0,0,nil
6/24 21:39:25.710  SPELL_CAST_FAILED,0x00000000000026BE,"Ihaz",0x511,0x0000000000000000,nil,0x80000000,57993,"Envenom",0x8,"That ability requires combo points"
6/24 21:39:25.827  SWING_DAMAGE,0x00000000000026BE,"Ihaz",0x511,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,1085,0,1,0,0,0,1,nil,nil
6/24 21:39:25.827  SPELL_ENERGIZE,0x00000000000026BE,"Ihaz",0x511,0x00000000000026BE,"Ihaz",0x511,51637,"Focused Attacks",0x1,2,3
6/24 21:39:25.827  SPELL_CAST_SUCCESS,0x00000000000026BE,"Ihaz",0x511,0x0000000000000000,nil,0x80000000,25733,"Unsurpassed Vigor",0x1
6/24 21:39:25.827  SPELL_HEAL,0x00000000000026BE,"Ihaz",0x511,0x00000000000026BE,"Ihaz",0x511,25733,"Unsurpassed Vigor",0x1,354,0,0,nil
6/24 21:39:26.061  SWING_DAMAGE,0x00000000000026BE,"Ihaz",0x511,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,265,0,1,0,0,0,nil,nil,nil
6/24 21:39:26.061  SPELL_CAST_SUCCESS,0x00000000000026BE,"Ihaz",0x511,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,57970,"Deadly Poison IX",0x8
6/24 21:39:26.094  SPELL_AURA_APPLIED_DOSE,0x00000000000026BE,"Ihaz",0x511,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,57970,"Deadly Poison IX",0x8,DEBUFF,3
6/24 21:39:26.277  SPELL_CAST_FAILED,0x00000000000026BE,"Ihaz",0x511,0x0000000000000000,nil,0x80000000,48666,"Mutilate",0x1,"Not yet recovered"
6/24 21:39:26.428  SPELL_CAST_FAILED,0x00000000000026BE,"Ihaz",0x511,0x0000000000000000,nil,0x80000000,48666,"Mutilate",0x1,"Not enough energy"
6/24 21:39:26.511  SPELL_PERIODIC_DAMAGE,0x00000000000026BE,"Ihaz",0x511,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,57970,"Deadly Poison IX",0x8,783,0,8,0,0,0,nil,nil,nil
6/24 21:39:26.511  SPELL_AURA_REMOVED,0x00000000000026BE,"Ihaz",0x511,0xF130007A1A01D951,"Ymirheim Chosen Warrior",0x10a48,1833,"Cheap Shot",0x1,DEBUFF
```

**Comment by UltraNix** [comment] 2024-07-08 18:47
Closing this one as there is no more info on this.

**Closed by UltraNix** 2024-07-08 18:47 UTC
Labels: Medium Prio
