### ISSUE TITLE
[TOGC] Faction champs

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#2470] opened 2024-11-29 18:04 UTC
Most of these bugs affect heroic(ascended?) some might also affect normal.

1. custom mobs do not have the 75% aoe reduction buff (demolock, elesham, demonhunter, bm hunter, feral) as such they can be stacked together and aoecleaved if one desires.
https://www.wowhead.com/wotlk/spell=68595/champions-aegis

2.
Spells the champions use mimic the ones players use, including their cooldown as you can see from wowhead (ex: blade flurry having same cd for champion as a player 2min)
We can use both wowhead and my point above to infer what cooldowns should be for both normal spells and custom tuning spells to stay true to the essence of this fight.

As such I report the following bugs and design flaws:
ROGUE:https://www.wowhead.com/wotlk/npc=34454/mazdinah#abilities;mode:h25
-shadowstep has 20sec cd instead of the intended 30sec
-rogue should have 2min killing spree has only 40sec instead (if based on the glyphed ks version cd should be 1min15sec)

WAR:
-Shockwave has 30sec cooldown instead of the 20sec protwar spell. https://www.wowhead.com/wotlk/spell=46968/shockwave

Demon hunter: (this mob is pretty broken)
BUGS:
-After the first flight phase he falls through the ground when he tries to land (even with the fixed floor on ptr)
You can't do anything to him while underground, while he can melee you from underground depending on position. He only resurges above for each flight phase then goes back underground.

-After the first flight phase he will not be rooted in his flight position to cast eyebeam, he will follow AND MELEE his eye beam target shortly before and after he finishes cast.

-Shadow prison stun can **very rarely** coincide with eyebeam, if done on the same person its unavoidable death

-Eyebeam ticks for 24-25k damage, this is twice the damage from actual frosthold end implementation, people could stay in it and outheal it while here it 1shots/2shots.

-Swarming shadows: the fire left behind's damage hitbox is too big, making it possible to take damage from 2 flames while inside one or INSIDE NONE.
-Swarming shadows: there is no grace period(arming period) when flame is dropped where they should deal no damage, as such paired with the hitbox bug above can cause players with normal movespeed to take damage while placing them and moving - which should be considered a bug.

DESIGN FLAWS:
-Eyebeam has 1sec after it targets a player until it fires oneshot damage. This is extremely bad design. Illidan's spell only works like this because he uses it on predetermined points on the floor(everyone knows from where to where the beam goes), while this one directly targets the player with low visual que since its a chaotic fight unlike the illidan encounter.
_Proposed solution 1:_ Increase "arming time" between choosing a player and firing the beam by decent amount AND increase the visual indication that he's going to cast the spell on that player(how? no clue, marker gobj, hunter mark visual effect?)
_Proposed solution 2:_ Make him cast it like illidan, not on the player but on the floor (maybe between the points of the star patter the arena has)
_Proposed solution 3:_ Make it do 8-12k dmg like on actual frosthold where people could ignore this completely as a mechanic and stay still+overheal (_wouldn't be my go-to solution as its basically watering down this mechanic)_

-Swarming shadows: each fire dropped has an 1s individual damage tick, if someone leaves a puddle of them by not moving, that puddle will become a 5x6k dmg ticks a second oneshot zone.
Combined with the larger hitbox, the same instakill zone will happen if someone chooses to place em neatly stacked together.
This is not necessarily wrong by itself but it feels wrong when combined with that chaotic fight and all other ground aoe's happening - since players can't realize visually if fires are stacked or not in a choice whether to pass through them for a second in order to avoid something more dangerous they might get randomly oneshot

Proposed solution: Make the flames not tick damage by themselves, instead staying in the fire gives the player a _nonstackable_ "Burning" debuff that damages them while inside the flames to solve the stacking fire ticks.
It is possible that solving the bugs above regarding this might be enough to not touch this in a custom way and lowering the impact of this mechanic so this is subjective.

https://vimeo.com/1034597247?share=copy#t=0
Video where some of these can be seen taken on ptr today.
Sorry for long post, don't have enough time to test other cooldowns for rest of champions so there might be more which I will add in time.
The most critical thing to fix right now is the demon hunter, he feels completely out of place as he is, I'd completely remove him but you'll probably go though the pain of fixing that hot mess just to keep him so I feel for you devs. Good luck and much respect as usual!

**Comment by Piootrek** [comment] 2024-12-02 10:57
> -Eyebeam ticks for 24-25k damage, this is twice the damage from actual frosthold end implementation, people could stay in it and outheal it while here it 1shots/2shots.

Not a bug

> -Swarming shadows: there is no grace period(arming period) when flame is dropped where they should deal no damage, as such paired with the hitbox bug above can cause players with normal movespeed to take damage while placing them and moving 

There is already 1s grace period

> -Eyebeam has 1sec after it targets a player until it fires oneshot damage. This is extremely bad design. Illidan's spell only works like this because he uses it on predetermined points on the floor(everyone knows from where to where the beam goes), while this one directly targets the player with low visual que since its a chaotic fight unlike the illidan encounter.

Added 2s timer between choosing target and casting the spell. In addition added indicator mark above target head

> -Swarming shadows: each fire dropped has an 1s individual damage tick, if someone leaves a puddle of them by not moving, that puddle will become a 5x6k dmg ticks a second oneshot zone.

I don't think that's the issue. 

Rest of the bugs got fixed. I will close this issue once the fix comes live,

**Comment by sputnikk** [comment] 2024-12-02 11:03
That looks like most of it, thanks for your work!

**Comment by sputnikk** [comment] 2024-12-02 11:11
Any chance this fix will be applied to ptr?

**Comment by Furiianda** [comment] 2024-12-04 02:40
Adding to general Faction Champ issues, some players reported the champions in 25m normal will focus down any Mage players first in the raid before any other player class. Not sure if this is intentional.

**Closed** 2024-12-04 11:20 UTC
Labels: High Prio
