### ISSUE TITLE
[Quest] The Defias Brotherhood (Part 6)

### ISSUE THREAD

**Issue by Furiianda** [gamefreedomgit/Frostmourne#2387] opened 2024-11-18 07:05 UTC
**Description:**
The NPC "The Defias Traitor" sometimes gets stuck and doesn't return to the original starting point of the escort quest.

**How to reproduce:**
Unfortunately unclear, at the time of writing, the NPC is stuck in Moonbrook near the end of the escort in a non-interactable state. Image: https://imgur.com/a/hEXCO7j

**How it should work:**
The Defias Traitor should be at Sentinel Hill to start the escort quest after a player either completes or fails their quest. Additionally, the NPC should probably be attackable by the surrounding Defias mobs. Currently they don't engage with each other (NPC is idle next to a hostile mob)

**Database links:**
https://www.wowhead.com/wotlk/npc=467/the-defias-traitor
https://www.wowhead.com/wotlk/quest=155/the-defias-brotherhood

**Comment by Piootrek** [comment] 2024-11-20 10:59
I couldn't reproduce this, but I've made some changes that might fix this issue. 
I will close this issue once the fix comes live.

**Closed** 2024-11-22 13:29 UTC
Labels: Medium Prio
