### ISSUE TITLE
[Ulduar] Switching to heroic

### ISSUE THREAD

**Issue by oneadanut** [gamefreedomgit/Frostmourne#2143] opened 2024-10-15 16:18 UTC
**Description:**
Sometimes you cannot see the error message when switching to heroic in Ulduar, making people believe it's bugged because it's not switching. The yellow message like "cannot switch until x seconds" doesn't appear. If you wait certain seconds, you can switch.

Maybe lower the amount of seconds needed after combat to be able to switch. Sometimes you cannot put heroic for 90 seconds, that's a waste of time.

**Comment by Piootrek** [comment] 2024-10-16 07:41
Hey, I couldn't reproduce this. When does it happen? After killing boss or before next boss? Any vod would be useful

**Comment by oneadanut** [comment] 2024-10-16 09:41
We killed Hodir on normal then we cleared trash to Thorim and we couldn't switch to heroic for Thorim. No error message appeared. After aprox 2 mins it worked. I wanted to record but game bar didn't allow me that time.

**Comment by oneadanut** [comment] 2024-10-27 21:50
I'll close this since it didn't happen anymore.

**Comment by oneadanut** [comment] 2024-11-14 21:32
It happened again right now, the leader couldn't switch to normal mode after we killed Vezax heroic. We were in front of the door of Yogg-Saron room, but one of the mages was disconnected and dead in Vezax room. It didnt work even changing the leader to someone else, they didn't get any error message.

After the afk mage was kicked from the raid and he got teleported, the switch to normal worked.
I guess the bug occurs when someone is dead.

**Comment by Piootrek** [comment] 2024-11-15 09:24
Fixed, I will close this issue once the fix comes live.

**Comment by oneadanut** [comment] 2024-11-17 19:00
Sometimes It doesn't work even if someone is in Dalaran.

**Closed** 2024-12-05 15:29 UTC
Labels: Medium Prio
