### ISSUE TITLE
Druid - Owlkin Frenzy not working

### ISSUE THREAD

**Issue by ffroehly** [gamefreedomgit/Frostmourne#1156] opened 2024-06-27 11:52 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
As a druid, there's a talent called "Owlkin Frenzy" that gives you more damages, mana regen and reduces pushabck when the talent procs.
However, both the mana regen and damage increase do not seem to be working.
On my screen, I do not get the +N mana written in blue, while the buff is active, and I do not see increase damages in my character stats when the talent procs.

**How to reproduce:**
Take a druid lvl 50 or more, put your talent point into Moonkin tree up until reaching 3//3 in Owlkin Frenzy talent, then get hit by a mob a few times and the talent Olwkin Frenzy should proc.
You can then see you will not regen mana, nor have damage increased.

**How it should work:**
![2024-06-27 13_52_14-Owlkin Frenzy - Spell - WotLK Classic](https://github.com/gamefreedomgit/Frostmourne/assets/86048865/0e04eba7-2aa5-49de-8442-a59ee6b397f9)

When talent proc, you should get:
- 2% mana returned every 2s
- 10% dmg increaded
- no pushback when spell casting

**Database links:**

**Comment by BalanCV** [comment] 2024-06-27 16:08
Is there anything special you are doing different? because I've had this talent  for a few weeks now and its working perfectly.
+mana gain tracked by MSBT addon
Procced during hurricane cast: dmg before 1700, dmg after it procced 1850 (10% more)

**Comment by Godmatik** [comment] 2024-06-27 18:47
Keep in mind also that most raid boss abilities do not proc owlkin frenzy, by design

**Comment by UltraNix** [comment] 2024-06-27 19:07
Also tested and see bug here:
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/af08619d-e878-4b7a-9dc3-a40cb708eb8d)
You can see the buff, the mana regen and increased damage.

**Comment by ffroehly** [comment] 2024-06-27 21:12
I was levling, and didn't see the mana as floating blue text around my character.
I am not lvl 80, I was around lvl 50

**Comment by yeagerca** [comment] 2024-06-28 00:38
Double check that your Combat Text is turned on for both Energy Gains and Periodic Energy Gains.

**Comment by WhitemaneIsa** [comment] 2024-08-14 19:16
No further info/complaints, closing.

**Closed by WhitemaneIsa** 2024-08-14 19:16 UTC
Labels: Need More Info from Reporter
