### ISSUE TITLE
Trial of Champions Ascended II

### ISSUE THREAD

**Issue by Tahtoh88** [gamefreedomgit/Frostmourne#2610] opened 2024-12-13 00:26 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Warrior intercept cooldown is too short, deals 15k damage following a killing blow autoattack, whirlwind cannot be disarmed, all enemy champions cannot be hexed
on 2nd boss paletress, holy smite deals overtuned damage and cannot be interupted, nor soaked with grounding totem, holy fire on the other hand deals lower damage than holy smite despite having a long cooldown

**How to reproduce:**
reconsult the 1st and 2nd ToC bosses above

**How it should work:**
toc should be tuned down

**Database links:**

**Comment by Piootrek** [comment] 2024-12-13 11:14
- Reduced Warrior Grand Champion Intercept damage and increased cooldown on Ascended difficulty
- Warrior Grand Champion Bladestorm should be interruptable with disarm
- Reduced Argent Confessor Paletress Holy Smite damage on Ascended difficulty

>  all enemy champions cannot be hexed

That's not a bug

I will close this issue once the fix comes live.

**Comment by Piootrek** [comment] 2024-12-13 13:19
> Thanks for the changes, about Paletress casts, could holy smite be also soaked from grounding totem, if holy fire get soaked, i believe holy smite should be as well, assuming the fact that her immunity to interrupts is intended

This spell has blizzard attribute "cant be redirected", so grounding totem shouldn't work on it.

**Closed** 2024-12-18 08:29 UTC
Labels: High Prio
