### ISSUE TITLE
CC through texture.

### ISSUE THREAD

**Issue by reminuz** [gamefreedomgit/Frostmourne#1979] opened 2024-09-24 18:26 UTC
Sometimes CC works through texture. It's game breaking in arena.
It happens a lot.
https://imgur.com/a/QmnQPNH

**Comment by UltraNix** [comment] 2024-09-25 07:33
@reminuz Video would be more helpful here, as I can't reproduce it.

**Comment by reminuz** [comment] 2024-09-25 10:18
Enemy cast a cc. ——> i go behind pillar while enemy is casting cc ——> i’m in cc behind pillar

**Comment by haephaistoss** [comment] 2024-09-25 11:57
Not sure I'm right but I recall something that may have something to do with it:

IIRC the client sends position packets every 400 ms or so
Based on that assumption it may be worth checking if aura application / cast finish can result in a success if enemy is already behind pillar, but the last position update showed that the target was not yet out of LoS. Maybe if this is the case, force a position check?

**Comment by Manpower99** [comment] 2024-09-25 14:54
Something like this was part of the original game also, as part of position checks every couple of ms. so if lucky/unlucky and your cast goes through before position check after LoS happens you can actually get hit through LoS
it was by request reduced in classic idk what your plan is here.
https://github.com/ClassicWoWCommunity/cata-classic-bugs/issues/124
you can view most of the vods and know that the bugreport is part of proposed changes added to classic to reduce some of these blizzlike inconsistencies that were result of server batching.
[Vod im referring to ](https://private-user-images.githubusercontent.com/107503518/177995300-c81add03-ae36-4f60-842d-814becd71f05.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNzYxNjcsIm5iZiI6MTcyNzI3NTg2NywicGF0aCI6Ii8xMDc1MDM1MTgvMTc3OTk1MzAwLWM4MWFkZDAzLWFlMzYtNGY2MC04NDJkLTgxNGJlY2Q3MWYwNS5tcDQ_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQxNDUxMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDVmMGUzMzgwNzRlNjRlYzRjMjQ0YmY5OGQ4NDczNmY3M2RhMDdhZGYwZmNkYTFlMDJiYTY0ODNhNWE1MGIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FFAdF2D_2Nsex3MOT1uW6IJV-v_XtdnOp3QbXqot0aw)

**Comment by reminuz** [comment] 2024-09-25 18:52
> @reminuz Video would be more helpful here, as I can't reproduce it.

https://streamable.com/4rcumf

**Comment by Riztazz** [comment] 2024-10-01 10:33
Yeah, it's nothing server-side imo, it's a combination of server current diff, MS and how client sends updates. I've seen the streamable link when it was active (no longer is). Almost always you're 'ahead' in the client than the server, when you move you send a position update packet (the 500ms is bullcrap most probably, server receives movement updates much much more often).
While on your screen you're probably behind a wall, on a server your move wasn't yet registered.
WOTLK didn't have server-side prediction as far as i know, so closing this.
On newer patches i suspect blizzard does implement prediction keys so it's does not happen as often

**Closed by Riztazz** 2024-10-01 10:33 UTC
Labels: Dev has a question
