### ISSUE TITLE
Hunter Traps randomly dissappearing/not working.

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1753] opened 2024-09-02 09:23 UTC
Occured while ptr testing and from other people telling me that it happened on live while testing on MPG.

 - Quite often Hunter traps go on a cd without them spawning/appearing.

Happened in Auriaya, Freya, Thorim, Hodir, Sapphiron, Malygos. could be more but i cannot confirm.

**Comment by Tednugg** [comment] 2024-09-04 12:09
Show video proof of it happening, otherwise the report is irrelevant

**Comment by Manpower99** [comment] 2024-09-04 12:50
Lol? perhaps you should be commenting elsewhere.

**Comment by UltraNix** [comment] 2024-09-05 07:42
@Manpower99 More info needed here. Any idea why it's happening? Maybe trap summoned under ground? Logs say it's been summoned?

**Comment by Manpower99** [comment] 2024-09-05 22:50
> @Manpower99 More info needed here. Any idea why it's happening? Maybe trap summoned under ground? Logs say it's been summoned?

![image](https://github.com/user-attachments/assets/cb95a935-0136-4e0d-b372-819956765086)

okay this is consistently happening, if you place a trap while moving near a wall or edge or tree, high chance it spawns in the air instead. screenshot here happened on SWP after the Twin boss.

**Comment by Tednugg** [comment] 2024-09-07 07:01
> Lol? perhaps you should be commenting elsewhere.

I don't know why you're getting defensive, I want this fixed more than you, it's just a bad report, no evidence, no explanation on how to reproduce the bug, how is this supposed to be tested? I am just saying you should provide more info, so the bug can be identified by the developers and fixed.

**Comment by Manpower99** [comment] 2024-09-07 09:14
> > Lol? perhaps you should be commenting elsewhere.
> 
> I don't know why you're getting defensive, I want this fixed more than you, it's just a bad report, no evidence, no explanation on how to reproduce the bug, how is this supposed to be tested? I am just saying you should provide more info, so the bug can be identified by the developers and fixed.

No worries i'll close it let it stay bugged and no one will benefit from a fix, for one i dont see you making any bug reports so theres no need to benefit either.

**Comment by Tednugg** [comment] 2024-09-07 10:58
> > > Lol? perhaps you should be commenting elsewhere.
> > 
> > 
> > I don't know why you're getting defensive, I want this fixed more than you, it's just a bad report, no evidence, no explanation on how to reproduce the bug, how is this supposed to be tested? I am just saying you should provide more info, so the bug can be identified by the developers and fixed.
> 
> No worries i'll close it let it stay bugged and no one will benefit from a fix, for one i dont see you making any bug reports so theres no need to benefit either.

Such a fragile ego, very mature of you.

**Comment by Tednugg** [comment] 2024-09-07 13:18
@UltraNix This is not resolved btw

**Comment by Tednugg** [comment] 2024-09-10 10:03
#1145 Seems to be related and explain why this is happening

**Comment by Piootrek** [comment] 2024-09-12 12:55
Fixed, I will close this issue once the fix comes live.

**Closed** 2024-09-18 14:16 UTC
Labels: High Prio
