### ISSUE TITLE
[PTR] heroic 25m Iron council spawns twice

### ISSUE THREAD

**Issue by NickZedd** [gamefreedomgit/Frostmourne#1605] opened 2024-08-16 10:56 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Two of every boss spawns, totaling six. It is possible to kill them in any order and whichever ones you kill 3rd and 6th seem to determine what achievement and loot you get.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Manpower99** [comment] 2024-08-16 11:48
General issue on 25HC Atm, happened to us  in XT Mimiron and Freya and possibly others too.
basically you get a duplicate of the bosses.

**Comment by Afgann** [comment] 2024-08-17 06:50
fixed

**Closed by Afgann** 2024-08-17 06:50 UTC
Labels: PTR
