### ISSUE TITLE
Mage clearcasting not working

### ISSUE THREAD

**Issue by qwerty12qwe** [gamefreedomgit/Frostmourne#1930] opened 2024-09-18 22:14 UTC
Description:
Talent "Arcane Concentration" clearcasting buff not used when it is procced in Arcane spec after spamming Arcane Blast also didnt work with Arcane Missiles. Can upload a video prove

How to reproduce:
Happened raiding on naxx10 man asc and then went to the dummies to confirm it was bugged

How it should work:
As wowhead says any damage spell that does damage its mana reduced to 100%

Database links:
https://www.wowhead.com/classic/spell=12577/arcane-concentration

**Comment by query-wow** [comment] 2024-09-18 23:04
It works on the first spell but the buff never gets removed https://youtu.be/UNq8m8JYUEM?t=294

**Comment by qwerty12qwe** [comment] 2024-09-19 00:41
tried it and the buff didnt aply even on the first damaging spell, not a visual bug

**Comment by Aeradel** [comment] 2024-09-19 01:54
Can confirm that this does not correctly negate the mana cost of Arcane Blast when used. I was able to get it working with Arcane Missiles without issue. 

[Here](https://www.youtube.com/watch?v=GggKySgRqyw) is an example video of the issue, including the combat log and the mana resource text in the middle of the screen. 

If [Missile Barrage](https://www.wowhead.com/wotlk/spell=54489/missile-barrage) is active, then Clearcasting is not used on Arcane Missiles - which is intended and likely the reason why the original reporter could not use Clearcasting + Arcane Missiles.

**Comment by qwerty12qwe** [comment] 2024-09-19 02:59
the reason i was talking about its that the clearcasting its not working with the Arcane Blast not with Arcane Missiles, u can confirm it on your own video at the last seconds

**Comment by Aeradel** [comment] 2024-09-19 03:02
Not sure what you're saying exactly - but Clearcasting was not consumed by Arcane Missiles within the last seconds initially because of Missile Barrage. Arcane Missiles then consumes Clearcasting when I used the ability again, after consuming Missile Barrage in the previous casting.

You are correct in that Arcane Blast does not consume Clearcasting as intended though.

**Comment by qwerty12qwe** [comment] 2024-09-19 03:07
why is that? wowhead says clearcast "reduces the mana cost of your next damage spell", following that description arcane blast should consume the buff and cost no mana

**Comment by Aeradel** [comment] 2024-09-19 03:10
> why is that? wowhead says clearcast "reduces the mana cost of your next damage spell", following that description arcane blast should consume the buff and cost no mana

I think we're confusing each other.

In your initial, you mentioned that 
> clearcasting buff not used when it is procced in Arcane spec after spamming Arcane Blast also didnt work with Arcane Missiles

You are correct in that Arcane Blast does not use the buff as it should. 

> also didnt work with Arcane Missiles

This part is not correct though. It works with Arcane Missiles. I suspect the reasoning you thought it didn't work was because it consumed a different buff first, which also negates the mana cost - so the Clearcasting buff was not consumed on the initial cast. If you cast again after consuming Missile Barrage, the buff that also negates the cost of Arcane Missiles, then Clearcasting will work fine with Arcane Missiles. 

> tried it and the buff didnt aply even on the first damaging spell, not a visual bug

Arcane Blast is the only spell I was having issues with. Every other spell seems to consume the buff and negate the mana cost, as intended.

**Comment by Piootrek** [comment] 2024-09-19 08:09
Fixed, I will close this issue once the fix comes live.

**Closed** 2024-09-23 09:51 UTC
Labels: High Prio
