### ISSUE TITLE
[Quest] The Cleansing

### ISSUE THREAD

**Issue by Aeradel** [gamefreedomgit/Frostmourne#1648] opened 2024-08-21 11:38 UTC
There is a horde and an alliance version to this quest.

The alliance version [11322] works fine.

The horde version [11317] does not work properly. The item (which is also used in the alliance version) can not be used. It can not be interacted with.

**Comment by Riztazz** [comment] 2024-08-21 12:16
duplicate of https://github.com/gamefreedomgit/Frostmourne/issues/1644 which im going to fix in a bit :P

**Closed by Riztazz** 2024-08-21 12:16 UTC
