### ISSUE TITLE
Decimation talent doesnt work properly.

### ISSUE THREAD

**Issue by Vagos19** [gamefreedomgit/Frostmourne#892] opened 2024-06-13 09:24 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description: While being in a dungeon i was doing my normal rotation and suddenly when i got Molten Core proc and the mob i was hitting went bellow 35% health i didn't get the decimation proc like i am supposed to. 

**How to reproduce: Get Molten Core proc and have a mob being below 35% health and start hitting it with incinerate.

**How it should work: Every time you use Shadowbolt or Incinerate and the mob is below 35% health you are 100% supposed to get Decimation proc if you have talented it.

**Database links: https://www.wowhead.com/wotlk/spell=63158/decimation

**Comment by UltraNix** [comment] 2024-06-13 10:03
As I can see, Incinerate is a "flying spell" - maybe before the spell landed and hit your target, it was again > 35%hp? What was that mob?

**Comment by Vagos19** [comment] 2024-06-13 11:37
It happened during a dungeon (HOL) and more than once. More like 5 times in the whole dungeon where i couldnt proc Decimation with incinerate spell and yes it did land on the mob.

**Comment by UltraNix** [comment] 2024-06-13 13:35
I mean - before your spell hit your target, maybe something healed your target and again was above 35% of hp?

**Comment by UltraNix** [comment] 2024-06-13 13:40
As I can see, when you hit with your spell, your target should be already under 35% hp.
So. e.g if you spell hits target above 35%hp and damages your target below 35%, then you need another cast to proc it.

**Comment by Vagos19** [comment] 2024-06-13 16:46
I hit the same mob in HOL hrc once around 34% and again below 30% and i didnt get decimation proc. This happened 5-6 times

**Comment by UltraNix** [comment] 2024-06-13 17:18
If possible - please record it, as I can't reproduce it on many mobs I've tested.

**Comment by WhitemaneIsa** [comment] 2024-06-27 09:00
As there has been no further info/complaints, this will be closed for now.

**Closed by WhitemaneIsa** 2024-06-27 09:00 UTC
Labels: Dev has a question
