### ISSUE TITLE
[Warrior] Defensive Stance threat multiplier not fully applied on login

### ISSUE THREAD

**Issue by oomshroom** [gamefreedomgit/Frostmourne#436] opened 2024-05-16 23:18 UTC
When logging into the game as a warrior in Defensive Stance, the threat multiplier of the stance is wrong (1.7x instead of 2.0735x) until you swap out of the stance and back in. Other parts of the stance may or may not be wrong as well, I haven't tested them.

**Comment by Manpower99** [comment] 2024-05-20 09:06
Yup noticed this yesterday, it seems to be of similar issue to the other stance bugs for warriors where if you login the amplifiers /buffs of the stances are bugged unless you swap out and in.

**Comment by Riztazz** [comment] 2024-09-05 11:46
I cannot reproduce this :/ can you provide more information? Were you dead when you logged in? Morphed into something?

**Comment by Riztazz** [comment] 2024-09-11 09:38
I was checking server values not client values and it was always correct;p possibly some stat desync https://github.com/gamefreedomgit/Frostmourne/issues/1832

**Comment by Piootrek** [comment] 2024-09-19 12:42
You were right and threat modifier was indeed incorrect. Fixed, I will close this issue once the fix comes live.

**Comment by scrublama** [comment] 2024-09-19 21:42
ppl have said on for so long but didnt have any proof on all the servers before lol

**Comment by Riztazz** [comment] 2024-09-20 09:20
In my defense, i've created the character using normal trainer and it turns out you need to use some of the custom systems whitemane uses for this issue to pop-up :P

**Comment by Manpower99** [comment] 2024-09-20 12:14
it is likely related to custom auto learn or caused by it, reported many bugs during beta relating to it, often learning incorrect spells or spell components instead of the spell itself.
Referring to https://github.com/gamefreedomgit/Frostmourne/issues/419
Players at the time would be in Berserk benefit+actual (battle/defensive) stance  ... or berserk benefit twice while in berserker stance.
issue was, the benefit is also increasing chance to be critted so a warrior would never be defense capped under regular circumstances so it was a massive issue also. luckily it was fixed fast but theres likely more things to be discovered in the future.
Thank you @Piootrek and @Riztazz !

**Comment by Riztazz** [comment] 2024-09-20 12:29
In fact the issue was caused due to berserker stance passive that players shouldnt know so that further explains the situation

**Closed** 2024-09-26 09:40 UTC
Labels: Medium Prio
