### ISSUE TITLE
[Ascended] [Utgarde Pinnacle] doesn't allow resurrection

### ISSUE THREAD

**Issue by Furiianda** [gamefreedomgit/Frostmourne#2343] opened 2024-11-14 02:47 UTC
**Description:**
Within Utgarde Pinnacle: Ascended, can't resurrect players who died (even if they have not released spirit), unless using Rebirth.

**How to reproduce:**
This is based on reports from multiple players.
One player stated you can't resurrect anyone after killing the first boss (Svala Sorrowgrave).
Another player only experienced the bug in the last boss's room, (King Ymiron) but was able to use Druid Rebirth only - despite not being in combat. Additionally, they were playing Horde and were unable to resurrect Alliance players.

**How it should work:**
Normal Resurrection Mechanics

**Database links:**
N/A

**Comment by Piootrek** [comment] 2024-11-14 11:16
I couldn't reproduce. Can you provide more information? Do they get error message "Target cannot be resurrected" or the target is unfriendly to them?

**Comment by Piootrek** [comment] 2024-11-25 10:07
Fixed, I will close this issue once the fix comes live.

**Closed** 2024-11-28 09:21 UTC
Labels: Medium Prio
