### ISSUE TITLE
[PVP] Combat mechanics

### ISSUE THREAD

**Issue by Murglr** [gamefreedomgit/Frostmourne#925] opened 2024-06-15 10:26 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** It is not possible to get in combat except directly interacting with an ennemy which shouldnt be the case

**How to reproduce:** Heal or dispel someone in combat 

**How it should work:** You should be able to get combat by healing /dispelling an ally (or pet) that is himself in combat 

Actions that will get you into combat Combat[edit](https://wowpedia.fandom.com/wiki/Combat?veaction=edit&section=undefined)[edit source](https://auth.fandom.com/signin?redirect=https%3A%2F%2Fwowpedia.fandom.com%2Fwiki%2FCombat%3Faction%3Dedit%26section%3D2&uselang=en)

    [Attacking](https://wowpedia.fandom.com/wiki/Attack).
    Casting an offensive [spell](https://wowpedia.fandom.com/wiki/Spell).
    Casting a [buff](https://wowpedia.fandom.com/wiki/Buff) or a [healing](https://wowpedia.fandom.com/wiki/Healing) spell on a unit that is in combat
    Getting on a [mob's](https://wowpedia.fandom.com/wiki/Mob) [aggro](https://wowpedia.fandom.com/wiki/Aggro) list.
    Certain bosses always put everyone in the group (or raid) in combat when engaged, regardless their distance from the boss.

**Database links:**  https://wowpedia.fandom.com/wiki/Combat#Actions_that_will_get_you_into_combat

**Comment by UltraNix** [comment] 2024-06-17 17:09
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/b22d2047-d026-4dd4-abe8-dacef67237cf)
I just got combat by healing an ally that is in combat.
@Murglr Can you record it?

**Comment by WhitemaneIsa** [comment] 2024-06-27 09:01
As there has been no further info/complaints, this will be closed for now.

**Comment by Murglr** [comment] 2024-08-13 11:23
Sorry i forgot to mention that to replicate the bug only players. have to be included.
combat in pve environment works fine but if you heal/ buff 1 player that is hitting on another player that is where it is non functionnal.
might or might have not gotten combat with heals or buffs when pets where included. could not replicate this too often either so im not sure

**Comment by UltraNix** [comment] 2024-08-22 14:32
![image](https://github.com/user-attachments/assets/e0ad5538-343a-4d10-86c6-427311f0316a)
Still cannot reproduce it.

**Comment by Piootrek** [comment] 2024-09-30 12:07
Cannot reproduce this too, closing.

**Closed by Piootrek** 2024-09-30 12:07 UTC
Labels: Dev has a question
